identifier: 94f06584-6496-4bd5-8bc7-44b21db7ed83
original_step_id: ab72574e-971e-4523-98cc-1acab267fd24
parent_step_ids:
- 57d2ac65-c5df-457b-a118-082375d01aae
- 2f42ed49-5e99-4eae-ae2d-8582c6818dde
- 0e6c7ae7-7bcf-460b-9a12-c915b696cc6c
parent_step_id: 57d2ac65-c5df-457b-a118-082375d01aae
previous_result_condition: '{"57d2ac65-c5df-457b-a118-082375d01aae": "", "2f42ed49-5e99-4eae-ae2d-8582c6818dde":
    "", "0e6c7ae7-7bcf-460b-9a12-c915b696cc6c": ""}'
instance_name: User Activity
is_automatic: true
name: GoogleChronicle_Execute UDM Query
is_skippable: false
description: 'Execute custom UDM query in Google Chronicle. Note: 120 action executions
    are allowed per hour.'
action_provider: Scripts
action_name: GoogleChronicle_Execute UDM Query
integration: GoogleChronicle
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: AutomaticEnvironment
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleChronicle_Execute UDM Query
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Query":"[Alert.SIEM_PRINCIPAL_USERS_QUERY]","Time Frame":"1 Hour Around
        Alert Time","Start Time":"","End Time":"","Max Results To Return":"50"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
