identifier: 1126b41f-46d6-49a8-9788-e9481e37000d
original_step_id: 1126b41f-46d6-49a8-9788-e9481e37000d
parent_step_ids:
- d56695dc-eac4-479a-a345-b3825a417344
parent_step_id: d56695dc-eac4-479a-a345-b3825a417344
previous_result_condition: '{"d56695dc-eac4-479a-a345-b3825a417344": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
