identifier: 9a00cc1a-f55c-451d-b96c-ec2fbac8d90f
original_step_id: 9a00cc1a-f55c-451d-b96c-ec2fbac8d90f
parent_step_ids:
- 48f96796-ca0d-436c-b53a-00adbb2c068c
parent_step_id: 48f96796-ca0d-436c-b53a-00adbb2c068c
previous_result_condition: '{"48f96796-ca0d-436c-b53a-00adbb2c068c": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
