identifier: 0e6858f2-34f0-4c3e-b906-e2b8be6c2e5f
original_step_id: 0e6858f2-34f0-4c3e-b906-e2b8be6c2e5f
parent_step_ids:
- cb396287-98ab-4aa6-90fd-0fe1d4c3fa7b
parent_step_id: cb396287-98ab-4aa6-90fd-0fe1d4c3fa7b
previous_result_condition: '{"cb396287-98ab-4aa6-90fd-0fe1d4c3fa7b": ""}'
instance_name: Alert Overview
is_automatic: true
name: GoogleChronicle_Get Detection Details
is_skippable: false
description: Fetch information about a detection in Google Chronicle.
action_provider: Scripts
action_name: GoogleChronicle_Get Detection Details
integration: GoogleChronicle
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: RetryConfiguration
    value: '{"Enabled":false,"IntervalInSeconds":30,"NumberOfRetries":1}'
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleChronicle_Get Detection Details
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Rule ID":"[Event.detection_1_ruleId]","Detection ID":"[Event.id]"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
