identifier: b4b3d73f-f7e0-436f-89bd-daaf3357762f
original_step_id: b4b3d73f-f7e0-436f-89bd-daaf3357762f
parent_step_ids:
- 6beabc83-b37a-43ee-bd93-7ff82c6aaf40
parent_step_id: 6beabc83-b37a-43ee-bd93-7ff82c6aaf40
previous_result_condition: '{"6beabc83-b37a-43ee-bd93-7ff82c6aaf40": ""}'
instance_name: GoogleSecops Enrichment
is_automatic: true
name: Google SecOps Enrichment
is_skippable: false
description: This block retrieves relevant details about users and assets involved
    in the case, enhancing the context available for analysis and subsequent actions
    within Google SecOps SOAR.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 581ea3f9-d57f-4558-89ec-dfba874e0f17
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"029f2e91-b2ac-443b-9ecf-afb37cdfde72","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Has
        Target Resource?","stepType":4},{"identifier":"218ae3e4-887f-4cb2-a4c7-bf78d49841d6","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails 2","stepType":0},{"identifier":"846fae5e-802c-4c01-97d1-e855e02b5567","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary Domains","stepType":0},{"identifier":"87a947f4-f5fb-4173-98c1-9f5bdf1d3c4b","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"User Activity","stepType":0},{"identifier":"947e57ed-c936-4702-bf68-be980ea14017","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails","stepType":0},{"identifier":"a2359297-9f7f-45ad-ae1d-c840bafa7e6e","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary URLs Entity Selection","stepType":0},{"identifier":"a610e811-23ef-4362-9fca-dab26dd82e05","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User Query","stepType":0},{"identifier":"b6e8ccec-f864-4112-8a2b-2dec6a5f63d1","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User and Email Query","stepType":0},{"identifier":"c5ebe198-7900-416f-b5c4-20a407cb8ada","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"Target Resource Activity","stepType":0},{"identifier":"da47270b-4785-4ebb-9317-8f13edde6878","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        User Query based on Param","stepType":4},{"identifier":"de0e8f2c-b792-4f9b-acd3-3219c864adc6","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Emails Query","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
