identifier: 237ba5f0-c7fd-442b-b1ab-b7d10720a46b
original_step_id: 237ba5f0-c7fd-442b-b1ab-b7d10720a46b
parent_step_ids:
- cc3f970c-a6b9-4663-a518-feaf8354f6d5
parent_step_id: cc3f970c-a6b9-4663-a518-feaf8354f6d5
previous_result_condition: '{"cc3f970c-a6b9-4663-a518-feaf8354f6d5": ""}'
instance_name: MITRE Enrichment
is_automatic: true
name: MITRE Enrichment
is_skippable: false
description: This block retrieves detailed information about MITRE ATT&CK techniques
    and their associated mitigations, providing valuable context to understand adversary
    behaviors and possible defensive actions.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 0804b0f6-9827-4dc1-bfc4-ccc7e71055b7
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"31eabec7-a2cc-460a-8c21-13969e531942","integration":"MitreAttck","actionName":"MitreAttck_Get
        Techniques Mitigations","instanceName":"Mitre Techniques Mitigations","stepType":0},{"identifier":"3610ff1a-058f-4525-9759-6c354140053c","integration":"MitreAttck","actionName":"MitreAttck_Get
        Techniques Details","instanceName":"Mitre Techniques Details","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
