identifier: d65fe4af-71ab-4f2a-ab4a-4d9a98fd59a5
original_step_id: d65fe4af-71ab-4f2a-ab4a-4d9a98fd59a5
parent_step_ids:
- 60f62c53-44aa-4caf-a4bf-1fbee97388ed
parent_step_id: 60f62c53-44aa-4caf-a4bf-1fbee97388ed
previous_result_condition: '{"60f62c53-44aa-4caf-a4bf-1fbee97388ed": ""}'
instance_name: Okta Remediation Block
is_automatic: true
name: Okta Remediation Block
is_skippable: false
description: "This block allows the playbook to perform remediation actions on Okta\
    \ users, including generating a one-time token to reset a user\u2019s password,\
    \ disabling the user, or taking no action as needed."
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 11009d79-db3f-4830-969e-19282b7e4255
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"1ebd3d21-c862-4c05-a8bc-41560fae48de","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"REMEDIATION Update User","stepType":0},{"identifier":"4d55b2b2-4558-4260-bbaa-d9a7bafe9b32","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Remediation Disable User Account","stepType":0},{"identifier":"4ea30102-5a02-417b-8d42-f51e7a2beece","integration":"Okta","actionName":"Okta_Get
        User","instanceName":"Get User","stepType":0},{"identifier":"5ae322b4-49a1-425c-a2fb-c81518fcfc45","integration":"Flow","actionName":"IfFlowCondition","instanceName":"User
        exists?","stepType":4},{"identifier":"6994b115-461c-40e4-a291-0f4904c6a7d2","integration":"Flow","actionName":"MultiChoiceQuestion","instanceName":"Containment
        Decision","stepType":1},{"identifier":"6e3597f0-2bf3-4097-a747-eb3e5ee04973","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Init Remediation","stepType":0},{"identifier":"a9fbb515-a981-45e9-95e4-19b913f1645d","integration":"Okta","actionName":"Okta_Disable
        User","instanceName":"Disable User","stepType":0},{"identifier":"aa476b8f-a3cf-45fd-a505-28737be5b8f6","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"REMEDIATION Not Update User","stepType":0},{"identifier":"ae15693e-a20c-421c-8b12-56ae8a7087b5","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"REMEDIATION No Users to update","stepType":0},{"identifier":"ba5bdf97-9207-4ae0-a727-6a83215c7bc0","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Init
        Remediation Variable","stepType":4},{"identifier":"c4ea3f1a-7ef9-4c1b-94a1-226a22d3ce1f","integration":"Okta","actionName":"Okta_Reset
        Password","instanceName":"Reset Password","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
