identifier: c97e4533-72e0-4a6c-802c-cfcbc9d2c564
original_step_id: c97e4533-72e0-4a6c-802c-cfcbc9d2c564
parent_step_ids: []
parent_step_id: ''
previous_result_condition: '{}'
instance_name: Enrich Entities
is_automatic: true
name: GoogleThreatIntelligence_Enrich Entities
is_skippable: false
description: 'Use the Enrich Entities action to enrich the Google SecOps entities
    using information from Google Threat Intelligence. This action runs on the following
    Google Secops entities: IP address, URL, Hostname, Domain, Hash, Threat Actor,
    CVE. This action supports only MD5, SHA-1, and SHA-256 hashes.'
action_provider: Scripts
action_name: GoogleThreatIntelligence_Enrich Entities
integration: GoogleThreatIntelligence
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: RetryConfiguration
    value: '{"Enabled":false,"IntervalInSeconds":30,"NumberOfRetries":1}'
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleThreatIntelligence_Enrich Entities
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Resubmit Entity":false,"Resubmit After (Days)":"30","Sandbox":"VirusTotal
        Jujubox","Retrieve Sandbox Analysis":false,"Fetch MITRE Details":false,"Lowest
        MITRE Technique Severity":"Medium","Retrieve Comments":true,"Max Comments
        To Return":"10"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: null
parallel_actions: []
step_debug_data: null
