identifier: eebeac2b-97b7-423f-9dd6-eba104448a6b
original_step_id: eebeac2b-97b7-423f-9dd6-eba104448a6b
parent_step_ids:
- 049f32e8-3e9b-4078-b1e4-cbe607969727
parent_step_id: 049f32e8-3e9b-4078-b1e4-cbe607969727
previous_result_condition: '{"049f32e8-3e9b-4078-b1e4-cbe607969727": "2"}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
