-   description: This block checks Google GTI sourced alerts against a SOAR custom
        list to find matches of targeted Industries.
    version: '0'
    item_name: High Risk Users Check - 5
    item_type: Block
    publish_time: 1783582628
    ticket_number: ''
