identifier: 84abe04a-5b3c-4b98-bb13-0436567ae7fb
original_step_id: 84abe04a-5b3c-4b98-bb13-0436567ae7fb
parent_step_ids:
- 890e23d6-7ce9-4200-83dd-ea38ecc08640
parent_step_id: 890e23d6-7ce9-4200-83dd-ea38ecc08640
previous_result_condition: '{"890e23d6-7ce9-4200-83dd-ea38ecc08640": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
