identifier: 87682a50-358b-48ee-a1a0-50a6a0977ae2
original_step_id: 24174aa0-315d-4707-af91-63dfec3dc449
parent_step_ids: []
parent_step_id: ''
previous_result_condition: '{}'
instance_name: Mitre Techniques Details
is_automatic: true
name: MitreAttck_Get Techniques Details
is_skippable: false
description: Retrieve detailed information about MITRE attack techniques.
action_provider: Scripts
action_name: MitreAttck_Get Techniques Details
integration: MitreAttck
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: RetryConfiguration
    value: '{"Enabled":false,"IntervalInSeconds":30,"NumberOfRetries":1}'
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: MitreAttck_Get Techniques Details
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Technique Identifier":"[Entity.Identifier]","Identifier Type":"External
        ID"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All threat signatures entities
parallel_actions: []
step_debug_data: null
