identifier: 4b6499b7-5497-4ef2-a49e-3988e8f8120b
original_step_id: 842c9390-5c3f-46de-ba7c-9ae183cc8a9f
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
