identifier: d82ab34e-7e6c-49a6-829e-bf213fbe902e
original_step_id: d82ab34e-7e6c-49a6-829e-bf213fbe902e
parent_step_ids:
- a2588edc-f544-4d9e-acf4-e61ab69f521b
parent_step_id: a2588edc-f544-4d9e-acf4-e61ab69f521b
previous_result_condition: '{"a2588edc-f544-4d9e-acf4-e61ab69f521b": "2"}'
instance_name: Force Password Update
is_automatic: false
name: AzureActiveDirectory_Force Password Update
is_skippable: false
description: Force password update for user so the user will have to change their
    password on next login. Action expects Siemplify user entity in username@domain
    format.
action_provider: Scripts
action_name: AzureActiveDirectory_Force Password Update
integration: AzureActiveDirectory
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: AzureActiveDirectory_Force Password Update
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All users
parallel_actions: []
step_debug_data: null
