identifier: e9943af9-e16d-4588-8908-073397839816
original_step_id: e9943af9-e16d-4588-8908-073397839816
parent_step_ids:
- 701cb853-ac0f-4819-bc90-443f262e1e1b
parent_step_id: 701cb853-ac0f-4819-bc90-443f262e1e1b
previous_result_condition: '{"701cb853-ac0f-4819-bc90-443f262e1e1b": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
