identifier: 111c7a04-ab75-4d04-b516-24d633dfd630
original_step_id: 111c7a04-ab75-4d04-b516-24d633dfd630
parent_step_ids:
- eb754a70-8f6e-4ad0-87d2-d3188df399ee
parent_step_id: eb754a70-8f6e-4ad0-87d2-d3188df399ee
previous_result_condition: '{"eb754a70-8f6e-4ad0-87d2-d3188df399ee": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
