identifier: eb754a70-8f6e-4ad0-87d2-d3188df399ee
original_step_id: eb754a70-8f6e-4ad0-87d2-d3188df399ee
parent_step_ids:
- f1d51335-c040-4dde-875f-f635b9eb86d5
parent_step_id: f1d51335-c040-4dde-875f-f635b9eb86d5
previous_result_condition: '{"f1d51335-c040-4dde-875f-f635b9eb86d5": "1"}'
instance_name: REMEDIATION Force Password Update
is_automatic: true
name: Tools_Set Context Value
is_skippable: false
description: The action sets a key and value in a specific context (alert or case)
action_provider: Scripts
action_name: Tools_Set Context Value
integration: Tools
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Set Context Value
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Value":"[Alert.REMEDIATION]<sep>During the investigation of the alert
        it was decided to force password(s) updates.","Key":"REMEDIATION","Scope":"Alert"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
