identifier: a2588edc-f544-4d9e-acf4-e61ab69f521b
original_step_id: a2588edc-f544-4d9e-acf4-e61ab69f521b
parent_step_ids:
- 7f506a0d-7268-4d12-965e-1366c1c64f69
- cad60464-56b0-4b69-a3b2-eace03cef7d0
parent_step_id: 7f506a0d-7268-4d12-965e-1366c1c64f69
previous_result_condition: '{"7f506a0d-7268-4d12-965e-1366c1c64f69": "", "cad60464-56b0-4b69-a3b2-eace03cef7d0":
    "2"}'
instance_name: Update Password or Disable Account?
is_automatic: false
name: MultiChoiceQuestion
is_skippable: false
description: This step conditions the progress of the playbook according to a question
    the analyst has to answer manually, would be used most for questions which can't
    be answered automatically
action_provider: Flow
action_name: MultiChoiceQuestion
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: multi_choice_question
parameters:
-   step_id: null
    playbook_id: null
    name: Answers
    value: '{"1":"Disable Account","2":"Force Password Update","3":"Ignore"}'
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: Question
    value: Do you want to Update Password or Disable Account?
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: null
parallel_actions: []
step_debug_data: null
