-   description: This block enhances case entities with Google Threat Intelligence
        enrichment information. Works for IPs, URLs, hostnames, domains, hashes (MD5,
        SHA-1, SHA-256), threat actors, and CVEs.
    version: '0'
    item_name: GTI Enrichment - 1
    item_type: Block
    publish_time: 1783582585
    ticket_number: ''
