identifier: 61c0d37c-8bdc-458e-b2b1-3e9b4489417d
original_step_id: 1a9dedcb-df14-436e-b936-c04ab3733345
parent_step_ids:
- d38af13a-8a90-412d-9d69-dc9a882f0b4b
parent_step_id: d38af13a-8a90-412d-9d69-dc9a882f0b4b
previous_result_condition: '{"d38af13a-8a90-412d-9d69-dc9a882f0b4b": ""}'
instance_name: Machine Logon Users
is_automatic: true
name: MicrosoftDefenderATP_Get Machine Logon Users
is_skippable: false
description: Get Machine Log on users
action_provider: Scripts
action_name: MicrosoftDefenderATP_Get Machine Logon Users
integration: MicrosoftDefenderATP
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: MicrosoftDefenderATP_Get Machine Logon Users
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
