identifier: e9914fa9-cc5e-482f-b5df-6c54022313ea
original_step_id: a20764ea-3027-42db-b675-b9c07e194d25
parent_step_ids:
- f6dc4d34-92ab-4daa-8430-117dc6ee476e
parent_step_id: f6dc4d34-92ab-4daa-8430-117dc6ee476e
previous_result_condition: '{"f6dc4d34-92ab-4daa-8430-117dc6ee476e": ""}'
instance_name: MicrosoftDefender Related Alerts
is_automatic: true
name: MicrosoftDefenderATP_Get Machine Related Alerts
is_skippable: false
description: Get Machine Related Alerts
action_provider: Scripts
action_name: MicrosoftDefenderATP_Get Machine Related Alerts
integration: MicrosoftDefenderATP
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: MicrosoftDefenderATP_Get Machine Related Alerts
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Status":"Unknown, New, InProgress, Resolved","Severity":"UnSpecified,
        Informational, Low, Medium, High","Category":"","Incident ID":""}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
