identifier: d38af13a-8a90-412d-9d69-dc9a882f0b4b
original_step_id: 116982f6-95bf-42a0-9c20-20cbc1e4874c
parent_step_ids: []
parent_step_id: ''
previous_result_condition: '{}'
instance_name: Microsoft Defender Enrich Entities
is_automatic: true
name: MicrosoftDefenderATP_Enrich Entities
is_skippable: false
description: 'This action allows a user to enrich Microsoft Defender ATP hosts, ips
    and file hashes. Note: File hash can be in sha1 or sha256 format.'
action_provider: Scripts
action_name: MicrosoftDefenderATP_Enrich Entities
integration: MicrosoftDefenderATP
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: MicrosoftDefenderATP_Enrich Entities
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
