identifier: 1ccaa204-a6db-41ca-a112-bb056ff1b9d3
original_step_id: 1ccaa204-a6db-41ca-a112-bb056ff1b9d3
parent_step_ids:
- e835198b-aab5-40ad-a774-28b2f5021894
parent_step_id: e835198b-aab5-40ad-a774-28b2f5021894
previous_result_condition: '{"e835198b-aab5-40ad-a774-28b2f5021894": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
