identifier: 206727ae-2e18-43cc-ae12-28892a4bbb65
is_enable: true
version: '0'
name: Google Workspace Enrichment - 3
description: This block enriches user entities with relevant information from Google
    Workspace, providing additional context to support investigation and response
    activities.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: Siemplify automation
execution_scope: 0
original_playbook_identifier: 206727ae-2e18-43cc-ae12-28892a4bbb65
creation_time_unix_time_in_ms: 1783492156875
modification_time_unix_time_in_ms: 1783582632686
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
