identifier: 81ff04a4-d4b6-470c-b31d-bc577d9a8d16
type_: case_data
logical_operator: or
conditions:
-   field_name: '[Alert.Name]'
    value: AWS
    match_type: starts_with
    custom_operator_name: null
-   field_name: '[Event.event_metadata_productName]'
    value: AWS
    match_type: contains
    custom_operator_name: null
-   field_name: '[Event.event_metadata_vendorName]'
    value: AMAZON
    match_type: contains
    custom_operator_name: null
