identifier: 0debfc7c-0550-42fe-9be4-e043e22cf97e
original_step_id: 1f79519e-0ae9-4f9d-a6b6-3c883774ad89
parent_step_ids:
- 981ac08e-c253-44b1-9274-c3c125334792
parent_step_id: 981ac08e-c253-44b1-9274-c3c125334792
previous_result_condition: '{"981ac08e-c253-44b1-9274-c3c125334792": "1"}'
instance_name: Isolate Machines?
is_automatic: false
name: MultiChoiceQuestion
is_skippable: false
description: This step conditions the progress of the playbook according to a question
    the analyst has to answer manually, would be used most for questions which can't
    be answered automatically
action_provider: Flow
action_name: MultiChoiceQuestion
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: multi_choice_question
parameters:
-   step_id: null
    playbook_id: null
    name: Answers
    value: '{"1":"Yes","2":"No"}'
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: Question
    value: Isolate Machines?
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: null
parallel_actions: []
step_debug_data: null
