identifier: 62ef9439-8bd8-4725-be39-c2f204394727
original_step_id: 5f25ea9e-92bb-42b4-a3b9-f51ab4bfa3d8
parent_step_ids:
- 0debfc7c-0550-42fe-9be4-e043e22cf97e
- 92e57735-bb82-46fd-8d09-cdf37438f6f6
parent_step_id: 0debfc7c-0550-42fe-9be4-e043e22cf97e
previous_result_condition: '{"0debfc7c-0550-42fe-9be4-e043e22cf97e": "2", "92e57735-bb82-46fd-8d09-cdf37438f6f6":
    "2"}'
instance_name: NO_COMPUTE_INSTANCE_REMEDIATION_SUMMARY
is_automatic: true
name: Tools_Set Context Value
is_skippable: false
description: The action sets a key and value in a specific context (alert or case)
action_provider: Scripts
action_name: Tools_Set Context Value
integration: Tools
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Set Context Value
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Value":"[Alert.REMEDIATION]<sep>During the investigation of the alert
        it was decided to not isolate the affected machines","Key":"REMEDIATION","Scope":"Alert"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
