identifier: de6bd596-bfa2-4b11-99bc-380e5a02e8e7
original_step_id: f6d48cfb-33f0-4d96-aa16-a35b897ffe23
parent_step_ids:
- 62ef9439-8bd8-4725-be39-c2f204394727
parent_step_id: 62ef9439-8bd8-4725-be39-c2f204394727
previous_result_condition: '{"62ef9439-8bd8-4725-be39-c2f204394727": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
