identifier: 80fed7ed-8868-4bcd-8c49-2423578d8ced
original_step_id: 80fed7ed-8868-4bcd-8c49-2423578d8ced
parent_step_ids:
- be848007-3f8c-43b6-9143-6d7755b35540
parent_step_id: be848007-3f8c-43b6-9143-6d7755b35540
previous_result_condition: '{"be848007-3f8c-43b6-9143-6d7755b35540": ""}'
instance_name: List Security Groups
is_automatic: true
name: AWSEC2_List Security Groups
is_skippable: false
description: Describes the specified security groups or all of your security groups.
    A security group is for use with instances either in the EC2-Classic platform
    or in a specific VPC. For more information, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html
action_provider: Scripts
action_name: AWSEC2_List Security Groups
integration: AWSEC2
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: AutomaticEnvironment
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: RetryConfiguration
    value: '{"Enabled":false,"IntervalInSeconds":30,"NumberOfRetries":1}'
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: AWSEC2_List Security Groups
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Security Group Names":"","Security Group IDs":"[List Instances - EC2.JsonResult|
        \"EC2_Instances.SecurityGroups.GroupId\"]","Tag Filters":"","Max Results":"50"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: null
parallel_actions: []
step_debug_data: null
