identifier: c6922973-54f8-4f18-adfc-343858ce7ebd
is_enable: true
version: '0'
name: Google SecOps Enrichment
description: This block retrieves relevant details about users and assets involved
    in the case, enhancing the context available for analysis and subsequent actions
    within Google SecOps SOAR.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- '*'
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: 6900fc46-2900-40ab-9d7c-479966cd22ec
execution_scope: 0
original_playbook_identifier: c6922973-54f8-4f18-adfc-343858ce7ebd
creation_time_unix_time_in_ms: 1783492087331
modification_time_unix_time_in_ms: 1783492087331
template_name: null
debug_data:
    debugBaseAlertId: OS PATCH EXECUTION FROM SERVICE ACCOUNT_A41B4F8E-1CEC-4F24-8E5F-6F0A5AB7E7DE
    debugAlertId: OS PATCH EXECUTION FROM SERVICE ACCOUNT1AE5A653-7A2A-4F50-A58A-E85BA0E8E38C
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
