identifier: 813b4f7f-3729-455c-b1ba-8b505978a624
original_step_id: 4749eb8c-4c1d-453f-981f-42731aa4bf8e
parent_step_ids:
- ed362eae-e9ba-4e8b-87e2-0cc8a9770e45
parent_step_id: ed362eae-e9ba-4e8b-87e2-0cc8a9770e45
previous_result_condition: '{"ed362eae-e9ba-4e8b-87e2-0cc8a9770e45": ""}'
instance_name: List Users
is_automatic: true
name: GSuite_List Users
is_skippable: false
description: List users present in account.
action_provider: Scripts
action_name: GSuite_List Users
integration: GSuite
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GSuite_List Users
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Customer ID":"","Domain":"","Manager Email":"","Return only Admin Accounts?":false,"Return
        only Delegated Admin Accounts?":false,"Return only Suspended Users?":false,"Org
        Unit Path":"","Department":"","Record Limit":"20","Custom Query Parameter":"","Return
        only users without 2fa?":false,"Email Addresses":"[Filter Principal User.SelectedEntities]"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All users
parallel_actions: []
step_debug_data: null
