identifier: 0e723f4b-113d-43fe-8fca-a8c5e6faac85
original_step_id: fadb627f-1ffb-4a42-bceb-36f1da29a53c
parent_step_ids:
- ed7daa7b-2997-465f-8855-2cd37690f357
parent_step_id: ed7daa7b-2997-465f-8855-2cd37690f357
previous_result_condition: '{"ed7daa7b-2997-465f-8855-2cd37690f357": ""}'
instance_name: Output_3
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
