identifier: db69c3f0-f4a2-4fc8-81f6-bab08a317570
original_step_id: 6b28687b-d8e4-456c-9245-4efca5239c30
parent_step_ids:
- 68c7434a-1d1c-4305-a01e-af84779e037d
parent_step_id: 68c7434a-1d1c-4305-a01e-af84779e037d
previous_result_condition: '{"68c7434a-1d1c-4305-a01e-af84779e037d": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
