identifier: ed7daa7b-2997-465f-8855-2cd37690f357
original_step_id: 8cc265a9-5444-44bd-b55c-341de1b81a8e
parent_step_ids:
- 617c391e-fb3b-4cbc-af31-5f50f7d13117
parent_step_id: 617c391e-fb3b-4cbc-af31-5f50f7d13117
previous_result_condition: '{"617c391e-fb3b-4cbc-af31-5f50f7d13117": "2"}'
instance_name: REMEDIATION Not Update User
is_automatic: true
name: Siemplify_Set Scope Context Value
is_skippable: false
description: 'Action sets a value for a key specified that is stored in the Siemplify
    database. Available scopes to get context values for: Alert, Case, Global. Action
    is not working on Siemplify entities. Note: Key Name parameter is case insensitive.'
action_provider: Scripts
action_name: Siemplify_Set Scope Context Value
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Set Scope Context Value
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Context Scope":"Alert","Key Name":"REMEDIATION","Key Value":"[Alert.REMEDIATION]<sep>During
        the investigation of the alert, it was decided not to update the user."}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
