identifier: 893d1f6a-fb76-4c05-9ea3-b6a5d5354322
type_: case_data
logical_operator: or
conditions:
-   field_name: '[Event.event_metadata_logType]'
    value: MICROSOFT_DEFENDER_ENDPOINT
    match_type: equal
    custom_operator_name: null
-   field_name: '[Event.event_metadata_logType]'
    value: MICROSOFT_DEFENDER_ENDPOINT_IOS
    match_type: equal
    custom_operator_name: null
-   field_name: '[Event.event_metadata_logType]'
    value: 'WINDOWS_DEFENDER_ATP

        '
    match_type: equal
    custom_operator_name: null
