identifier: edc55c35-33cc-4285-bdfa-972358ffc9b6
original_step_id: edc55c35-33cc-4285-bdfa-972358ffc9b6
parent_step_ids:
- 24f9fa92-235a-481d-9490-4361425ed7ad
parent_step_id: 24f9fa92-235a-481d-9490-4361425ed7ad
previous_result_condition: '{"24f9fa92-235a-481d-9490-4361425ed7ad": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
