identifier: 0eea6ceb-7256-409f-acf7-623f6cc6bc94
original_step_id: 0eea6ceb-7256-409f-acf7-623f6cc6bc94
parent_step_ids:
- a37590d3-f491-4bf9-b5e0-3d3b0857b9ef
parent_step_id: a37590d3-f491-4bf9-b5e0-3d3b0857b9ef
previous_result_condition: '{"a37590d3-f491-4bf9-b5e0-3d3b0857b9ef": "2"}'
instance_name: Output_3
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
