identifier: 94ae171c-09ef-471b-8eec-a1fea58d100b
is_enable: true
version: '0'
name: Okta Enrichment
description: This block retrieves information about a user from Okta, including all
    roles assigned to the user and the groups the user is a member of, providing additional
    context for analysis and response actions.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: 6900fc46-2900-40ab-9d7c-479966cd22ec
execution_scope: 0
original_playbook_identifier: 94ae171c-09ef-471b-8eec-a1fea58d100b
creation_time_unix_time_in_ms: 1783492168393
modification_time_unix_time_in_ms: 1783492168393
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
