identifier: fa1ded53-f4f7-4fc4-a266-75ce310f819c
is_enable: true
version: '1'
name: New Playbook - 1
description: ''
priority: 2
category_name: Default
category: 1
environments:
- Default Environment
is_debug_mode: false
type: playbook
creator: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
modified_by: Siemplify automation
execution_scope: 1
original_playbook_identifier: fa1ded53-f4f7-4fc4-a266-75ce310f819c
creation_time_unix_time_in_ms: 1783401407775
modification_time_unix_time_in_ms: 1783401407775
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
