identifier: ccd91078-014b-453c-8a3d-d41bcdc8fe39
is_enable: true
version: '1'
name: New Block
description: An embedded workflow that can receive inputs and return an output.
priority: 2
category_name: New Folder
category: 3
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
modified_by: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
execution_scope: 0
original_playbook_identifier: ccd91078-014b-453c-8a3d-d41bcdc8fe39
creation_time_unix_time_in_ms: 1782888510519
modification_time_unix_time_in_ms: 1782888510519
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
