identifier: 4cbbd500-b494-42cc-86f6-680aa972f939
original_step_id: 4cbbd500-b494-42cc-86f6-680aa972f939
parent_step_ids:
- a7612a7b-13bb-4317-8ff4-16501a5892ad
parent_step_id: a7612a7b-13bb-4317-8ff4-16501a5892ad
previous_result_condition: '{"a7612a7b-13bb-4317-8ff4-16501a5892ad": ""}'
instance_name: Enrich User
is_automatic: true
name: AzureActiveDirectory_Enrich User
is_skippable: false
description: Enrich Siemplify User entity with information from Azure Active Directory.
    Action expects Siemplify user entity in username@domain format.
action_provider: Scripts
action_name: AzureActiveDirectory_Enrich User
integration: AzureActiveDirectory
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: AzureActiveDirectory_Enrich User
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Fields To Return":"accountEnabled,ageGroup,assignedLicenses,businessPhones,city,companyName,consentProvidedForMinor,country,createdDateTime,creationType,department,displayName,mail,employeeId,employeeHireDate,employeeOrgData,employeeType,onPremisesExtensionAttributes,externalUserStateChangeDateTime,faxNumber,givenName,imAddresses,identities,externalUserState,jobTitle,surname,lastPasswordChangeDateTime,legalAgeGroupClassification,mailNickname,mobilePhone,id,officeLocation,onPremisesSamAccountName,onPremisesDistinguishedName,onPremisesDomainName,onPremisesImmutableId,onPremisesLastSyncDateTime,onPremisesProvisioningErrors,onPremisesSecurityIdentifier,onPremisesSyncEnabled,onPremisesUserPrincipalName,otherMails,passwordPolicies,passwordProfile,preferredDataLocation,preferredLanguage,proxyAddresses,signInSessionsValidFromDateTime,sponsors,state,streetAddress,usageLocation,userPrincipalName,userType,postalCode,authorizationInfo,deletedDateTime,showInAddressList,isResourceAccount,refreshTokensValidFromDateTime"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
