identifier: c8c5b4ff-2043-4ce2-88d4-036d49c218f4
original_step_id: c8c5b4ff-2043-4ce2-88d4-036d49c218f4
parent_step_ids:
- 4cbbd500-b494-42cc-86f6-680aa972f939
parent_step_id: 4cbbd500-b494-42cc-86f6-680aa972f939
previous_result_condition: '{"4cbbd500-b494-42cc-86f6-680aa972f939": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
