identifier: d6a95c47-a094-4a9d-9ab6-b76a8c9e070b
original_step_id: 8f9f3ed7-b76f-4044-a44b-dc2a4493dea4
parent_step_ids:
- d475ce8a-7017-4a20-9d93-cf4ca0fd3643
parent_step_id: d475ce8a-7017-4a20-9d93-cf4ca0fd3643
previous_result_condition: '{"d475ce8a-7017-4a20-9d93-cf4ca0fd3643": "2"}'
instance_name: Output_3
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
