identifier: 3686316b-7077-46ab-b343-bef237d2ba6e
original_step_id: 56e8cf1b-537f-4dc8-9f41-c517582769ab
parent_step_ids:
- d373ad1c-42c6-4b4b-b18c-febc200b98c0
parent_step_id: d373ad1c-42c6-4b4b-b18c-febc200b98c0
previous_result_condition: '{"d373ad1c-42c6-4b4b-b18c-febc200b98c0": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
