identifier: e7ff88fd-cc3b-4f8c-89e5-964b142c373a
original_step_id: e7ff88fd-cc3b-4f8c-89e5-964b142c373a
parent_step_ids:
- 70d3511a-fec2-4d60-b2c7-47ccf911e11f
parent_step_id: 70d3511a-fec2-4d60-b2c7-47ccf911e11f
previous_result_condition: '{"70d3511a-fec2-4d60-b2c7-47ccf911e11f": ""}'
instance_name: Alert Overview
is_automatic: true
name: GoogleChronicle_Get Detection Details
is_skippable: false
description: Fetch information about a detection in Google Chronicle.
action_provider: Scripts
action_name: GoogleChronicle_Get Detection Details
integration: GoogleChronicle
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleChronicle_Get Detection Details
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Rule ID":"[Event.detection_1_ruleId]","Detection ID":"[Event.id]"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
