identifier: 51d76b82-4d28-43b1-a53a-bf86d22c6bd7
original_step_id: 51d76b82-4d28-43b1-a53a-bf86d22c6bd7
parent_step_ids:
- 35cefdf6-d573-49df-9207-18ddcf66f103
parent_step_id: 35cefdf6-d573-49df-9207-18ddcf66f103
previous_result_condition: '{"35cefdf6-d573-49df-9207-18ddcf66f103": ""}'
instance_name: AWS Enrichment
is_automatic: true
name: AWS Enrichment
is_skippable: false
description: This block retrieves EC2 instance data associated with the case and provides
    context for other actions or analysis.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 4de33f5f-73f0-4a7f-8af4-35a52a3bfd82
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"49b09ec1-26e8-4416-a6e8-9a71b6c3b60b","integration":"Flow","actionName":"EntitySelection","instanceName":"AWS
        EC2 Filter","stepType":0},{"identifier":"82b80e88-9ee7-497f-8d92-9a53305f04ea","integration":"Functions","actionName":"Functions_String
        Functions","instanceName":"Instance Ids","stepType":0},{"identifier":"f2d9b753-eb20-42ed-902a-370e8c0464ca","integration":"AWSEC2","actionName":"AWSEC2_List
        Instances","instanceName":"List Instances - EC2","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
