identifier: 81a26e46-6bc7-4c17-987f-755cfebb6ec6
original_step_id: 81a26e46-6bc7-4c17-987f-755cfebb6ec6
instance_name: Change Case Name
is_automatic: true
name: Tools_Change Case Name
is_skippable: false
description: The action changes the case's name (title)
action_provider: Scripts
action_name: Tools_Change Case Name
integration: Tools
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Change Case Name
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"New Name":"AWS Compute : [Event.detection_1_ruleName]","Only If First
        Alert":false}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
