identifier: a2077522-87fc-4c07-bcd9-82f0fc9faed3
original_step_id: a2077522-87fc-4c07-bcd9-82f0fc9faed3
parent_step_ids:
- 7b36e976-5efd-4175-8d7f-2f28201bcec0
parent_step_id: 7b36e976-5efd-4175-8d7f-2f28201bcec0
previous_result_condition: '{"7b36e976-5efd-4175-8d7f-2f28201bcec0": ""}'
instance_name: Change Case Name
is_automatic: true
name: Tools_Change Case Name
is_skippable: false
description: The action changes the case's name (title)
action_provider: Scripts
action_name: Tools_Change Case Name
integration: Tools
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: AutomaticEnvironment
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Change Case Name
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"New Name":"AWS Compute : [Event.detection_1_ruleName]","Only If First
        Alert":false}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
