identifier: 166904ad-7a23-4cc1-9396-55a41aef2f2b
original_step_id: 166904ad-7a23-4cc1-9396-55a41aef2f2b
instance_name: Google SecOps Enrichment_1
is_automatic: true
name: Google SecOps Enrichment
is_skippable: false
description: This block retrieves relevant details about users and assets involved
    in the case, enhancing the context available for analysis and subsequent actions
    within Google SecOps SOAR.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: c6922973-54f8-4f18-adfc-343858ce7ebd
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"030b64c2-75c7-4f9d-9fed-9167dd2704d7","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary URLs Entity Selection","stepType":0},{"identifier":"05143e04-8380-44c1-8ef8-4ae376265a20","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Has
        Target Resource?","stepType":4},{"identifier":"0e6c7ae7-7bcf-460b-9a12-c915b696cc6c","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Emails Query","stepType":0},{"identifier":"2f42ed49-5e99-4eae-ae2d-8582c6818dde","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User Query","stepType":0},{"identifier":"530a7963-3c89-4d60-8866-0b797f5c7c0d","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        User Query based on Param","stepType":4},{"identifier":"57d2ac65-c5df-457b-a118-082375d01aae","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User and Email Query","stepType":0},{"identifier":"6efa9565-952d-4df4-9bea-607af1ce99e2","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary Domains","stepType":0},{"identifier":"94f06584-6496-4bd5-8bc7-44b21db7ed83","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"User Activity","stepType":0},{"identifier":"a36e5f81-3ba1-4162-b643-2ca03765186f","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails","stepType":0},{"identifier":"d96be8f0-c843-4097-b42c-02d764b28d13","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails 2","stepType":0},{"identifier":"e035e89c-0b01-4c05-bafa-2a6624f5f4fb","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"Target Resource Activity","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
