identifier: 223f9427-1fbf-4359-9773-5b909593c966
original_step_id: 223f9427-1fbf-4359-9773-5b909593c966
instance_name: MITRE Enrichment
is_automatic: true
name: MITRE Enrichment
is_skippable: false
description: This block retrieves detailed information about MITRE ATT&CK techniques
    and their associated mitigations, providing valuable context to understand adversary
    behaviors and possible defensive actions.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: a1e02a4e-941a-4c59-b86e-9e82bc9ad0bb
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"71bb4ec2-1d01-47bd-b004-896c38d293a7","integration":"MitreAttck","actionName":"MitreAttck_Get
        Techniques Mitigations","instanceName":"Mitre Techniques Mitigations","stepType":0},{"identifier":"87682a50-358b-48ee-a1a0-50a6a0977ae2","integration":"MitreAttck","actionName":"MitreAttck_Get
        Techniques Details","instanceName":"Mitre Techniques Details","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
