identifier: a3d121f4-4a3c-4395-b635-adadf957124e
original_step_id: a3d121f4-4a3c-4395-b635-adadf957124e
parent_step_ids:
- e7ff88fd-cc3b-4f8c-89e5-964b142c373a
parent_step_id: e7ff88fd-cc3b-4f8c-89e5-964b142c373a
previous_result_condition: '{"e7ff88fd-cc3b-4f8c-89e5-964b142c373a": ""}'
instance_name: Set Initial Severity
is_automatic: true
name: Set Initial Severity
is_skippable: false
description: This block sets the initial alert score based on the SIEM detection severity
    or the rule metadata severity label.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 07119bba-c42f-4fdb-87ac-d19bb473c3b1
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"203c2a1f-b88b-46e5-b315-61998efe4a00","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Initi Summary","stepType":0},{"identifier":"3d9783d5-60ee-4168-b6f3-0273cfd3cb0c","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Fallback","stepType":0},{"identifier":"4f811461-0721-4c64-a3c5-b97e94e419f9","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        by alert severity ","stepType":4},{"identifier":"8932fde3-18e1-4162-aad4-7a830e248554","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +25","stepType":0},{"identifier":"98df5c61-e75d-4d53-b30b-c89cdabc6a06","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +75","stepType":0},{"identifier":"c1d59930-6f6b-4d60-896f-54c9471fcdd1","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +50","stepType":0},{"identifier":"d779f24f-d535-4cc1-8090-d0a04cde417a","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +90","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
