identifier: 42eaf0fc-4e84-43b4-851b-0004da4e5301
original_step_id: 42eaf0fc-4e84-43b4-851b-0004da4e5301
parent_step_ids:
- d74818e5-64d9-49a7-bb1e-340562c7e3e8
parent_step_id: d74818e5-64d9-49a7-bb1e-340562c7e3e8
previous_result_condition: '{"d74818e5-64d9-49a7-bb1e-340562c7e3e8": ""}'
instance_name: Alert Priority
is_automatic: true
name: Alert Priority
is_skippable: false
description: This block sets the alert priority using a previously defined playbook
    variable, ensuring consistent prioritization logic for the case workflow.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 02425e25-0017-4a63-9954-63c9ef9fa908
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"055d305a-b001-45d9-8d1c-8d726fc472d3","integration":"Siemplify","actionName":"Siemplify_Raise
        Incident","instanceName":"Raise Incident","stepType":0},{"identifier":"4189d040-efa1-420c-bed5-3db89d194305","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"CRITICAL","stepType":0},{"identifier":"521faafd-8746-43ba-a2ad-6395bc87d646","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"HIGH ","stepType":0},{"identifier":"5b6d1b50-54a6-44ce-bccd-def46900bdc3","integration":"Siemplify","actionName":"Siemplify_Change
        Case Stage","instanceName":"Case Stage Investigation","stepType":0},{"identifier":"7459679a-bcc2-4b1e-b415-db4f8359747d","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"LOW  ","stepType":0},{"identifier":"9889c154-a081-4822-bcb9-0707d2e9c7e8","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Inconclusive - Update Alert Summary","stepType":0},{"identifier":"9ae8c358-48e2-4ddd-8991-6195e25b0d96","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"INFORMATIONAL","stepType":0},{"identifier":"c5d14d34-cda3-471e-a57e-4c44f7e23ef4","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Assign
        Priority","stepType":4},{"identifier":"cfb83ec8-57ae-4cca-ada5-a8ff04068091","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"MEDIUM","stepType":0},{"identifier":"f8a685ec-90c4-4fa7-8589-97d2a189d019","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"RISKY - Update Alert Summary 2","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
