identifier: d74818e5-64d9-49a7-bb1e-340562c7e3e8
original_step_id: d74818e5-64d9-49a7-bb1e-340562c7e3e8
parent_step_ids:
- 0b95fbf7-4db4-49f3-8b3d-c4f444f52752
parent_step_id: 0b95fbf7-4db4-49f3-8b3d-c4f444f52752
previous_result_condition: '{"0b95fbf7-4db4-49f3-8b3d-c4f444f52752": ""}'
instance_name: Azure Enrichment
is_automatic: true
name: Azure Enrichment
is_skippable: false
description: This block enriches Siemplify Host and User entities with relevant information
    from Azure Active Directory, providing additional context to support investigation
    and response activities.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 0e06b0d0-87d2-4903-9093-24742ceab70a
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"50b1687c-a160-4ecd-ae87-1c91062a772b","integration":"AzureActiveDirectory","actionName":"AzureActiveDirectory_Enrich
        User","instanceName":"Enrich User","stepType":0},{"identifier":"faf20e08-accc-4592-b0df-870b3c1b49de","integration":"AzureActiveDirectory","actionName":"AzureActiveDirectory_Enrich
        Host","instanceName":"Enrich Host","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
