identifier: dc67648d-76c3-4c6d-aecc-41c6e0e0ca04
original_step_id: dc67648d-76c3-4c6d-aecc-41c6e0e0ca04
parent_step_ids:
- ec6dc8cf-db3b-4861-8856-bce986c7e6ea
parent_step_id: ec6dc8cf-db3b-4861-8856-bce986c7e6ea
previous_result_condition: '{"ec6dc8cf-db3b-4861-8856-bce986c7e6ea": ""}'
instance_name: Cloud Tag
is_automatic: true
name: Siemplify_Case Tag
is_skippable: false
description: Add given tag to the case the current alert is grouped to
action_provider: Scripts
action_name: Siemplify_Case Tag
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Case Tag
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Tag":"Cloud"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
