identifier: 70ee0545-9612-44dd-9ebd-8f95d8fbdf89
original_step_id: 70ee0545-9612-44dd-9ebd-8f95d8fbdf89
parent_step_ids:
- bd31a28a-1df0-43ed-9448-5a53ab0974ab
parent_step_id: bd31a28a-1df0-43ed-9448-5a53ab0974ab
previous_result_condition: '{"bd31a28a-1df0-43ed-9448-5a53ab0974ab": ""}'
instance_name: GTI Enrichment
is_automatic: true
name: GTI Enrichment
is_skippable: false
description: This block enhances case entities with Google Threat Intelligence enrichment
    information. Works for IPs, URLs, hostnames, domains, hashes (MD5, SHA-1, SHA-256),
    threat actors, and CVEs.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: b53d4d02-28b5-47ca-b962-b6780c65ad5b
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: 'true'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"2d40754b-409c-442a-80ac-66530512aa39","integration":"Tools","actionName":"Tools_Add
        Alert Scoring Information","instanceName":"Add Alert Scoring Information","stepType":0},{"identifier":"30c11474-9449-4107-9912-5050d8a63759","integration":"Tools","actionName":"Tools_Add
        Alert Scoring Information","instanceName":"Add Alert Scoring Information Risky","stepType":0},{"identifier":"b5ec87de-3a47-4a38-a275-f84302880163","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Risky
        entities? ","stepType":4},{"identifier":"c97e4533-72e0-4a6c-802c-cfcbc9d2c564","integration":"GoogleThreatIntelligence","actionName":"GoogleThreatIntelligence_Enrich
        Entities","instanceName":"Enrich Entities","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
