identifier: e4d3c82c-5926-484b-ad9c-83945db9b067
original_step_id: e4d3c82c-5926-484b-ad9c-83945db9b067
parent_step_ids:
- b1fe6c29-cd3a-472f-8507-1fd63fbca359
parent_step_id: b1fe6c29-cd3a-472f-8507-1fd63fbca359
previous_result_condition: '{"b1fe6c29-cd3a-472f-8507-1fd63fbca359": ""}'
instance_name: Ignore Unnecessary Domains
is_automatic: true
name: Entity Selection
is_skippable: false
description: Creates a group of entities that can be used in other actions. Use conditions
    to fine tune the group.
action_provider: Flow
action_name: EntitySelection
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: ConditionOperator
    value: '0'
-   step_id: null
    playbook_id: null
    name: Conditions
    value: '[{"FieldName":"Entity.Identifier","Operator":6,"Value":"GOOGLEAPIS.COM","Type":2},{"FieldName":"Entity.Identifier","Operator":6,"Value":"GOOGLE.COM","Type":2},{"FieldName":"Entity.Identifier","Operator":6,"Value":"MITRE.ORG","Type":2},{"FieldName":"Entity.Identifier","Operator":6,"Value":"VIRUSTOTAL.COM","Type":2},{"FieldName":"Entity.IsInternalAsset","Operator":5,"Type":2,"Value":"True"}]'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
