-   description: This block enriches user entities with relevant information from
        Google Workspace, providing additional context to support investigation and
        response activities.
    version: '0'
    item_name: Google Workspace Enrichment
    item_type: Block
    publish_time: 1783582651
    ticket_number: ''
