identifier: 1caf4897-2481-4ec4-ae34-1975e613048e
original_step_id: 1caf4897-2481-4ec4-ae34-1975e613048e
parent_step_ids:
- e9f839cc-1bd7-436e-8d50-64438a226ffc
- fee996dc-55b5-4f7c-b2f5-1a9517501563
parent_step_id: e9f839cc-1bd7-436e-8d50-64438a226ffc
previous_result_condition: '{"e9f839cc-1bd7-436e-8d50-64438a226ffc": "", "fee996dc-55b5-4f7c-b2f5-1a9517501563":
    "4"}'
instance_name: Has Target Resource?
is_automatic: true
name: Condition
is_skippable: false
description: This condition determines the progress of the playbook. Conditions are
    built based on cases data (cases, alerts, vents, entities and environment properties)
    as-well as data that comes back from previous playbook steps.
action_provider: Flow
action_name: IfFlowCondition
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: condition
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: Branches
    value: '[{"LogicalOperator":0,"Conditions":[{"Operator":8,"FieldName":"[Event.event_target_resource_name]","Type":2,"Value":"","CustomOperatorName":null}],"Order":1,"IsDefaultBranch":false,"Name":"Yes"},{"LogicalOperator":0,"Conditions":[],"Order":2,"IsDefaultBranch":true,"Name":"Branch"}]'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: ErrorFallbackBranch
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
