identifier: 9dcc4bc8-964f-4b28-a187-75c76eee3b95
original_step_id: 9dcc4bc8-964f-4b28-a187-75c76eee3b95
parent_step_ids: []
parent_step_id: ''
previous_result_condition: '{}'
instance_name: Ignore Unnecessary URLs Entity Selection
is_automatic: true
name: Entity Selection
is_skippable: false
description: Creates a group of entities that can be used in other actions. Use conditions
    to fine tune the group.
action_provider: Flow
action_name: EntitySelection
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: ConditionOperator
    value: '0'
-   step_id: null
    playbook_id: null
    name: Conditions
    value: '[{"FieldName":"Entity.Identifier","Operator":6,"Value":"HTTPS://WWW.VIRUSTOTAL","Type":2},{"FieldName":"Entity.Identifier","Operator":6,"Value":"HTTPS://CONSOLE.CLOUD.GOOGLE.COM","Type":2},{"FieldName":"Entity.Identifier","Operator":6,"Value":"HTTPS://ATTACK.MITRE.ORG","Type":2},{"FieldName":"Entity.Type","Operator":0,"Value":"DestinationURL","Type":2}]'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
