identifier: a54d1e36-969d-4e88-bb50-7c84d0b12511
original_step_id: a54d1e36-969d-4e88-bb50-7c84d0b12511
parent_step_ids:
- f420dd11-e152-4eb0-aa42-aa1d14eaf290
parent_step_id: f420dd11-e152-4eb0-aa42-aa1d14eaf290
previous_result_condition: '{"f420dd11-e152-4eb0-aa42-aa1d14eaf290": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
