identifier: b861cf33-76c4-4bbd-9ee4-d90c608297ae
original_step_id: b861cf33-76c4-4bbd-9ee4-d90c608297ae
parent_step_ids:
- a10c13d2-6f18-476e-afde-d85ca3da96ee
parent_step_id: a10c13d2-6f18-476e-afde-d85ca3da96ee
previous_result_condition: '{"a10c13d2-6f18-476e-afde-d85ca3da96ee": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
