identifier: 7064d290-466e-48c4-9d33-e0cdaef6c1b4
original_step_id: 7064d290-466e-48c4-9d33-e0cdaef6c1b4
parent_step_ids:
- 63a93b87-8082-48af-9d09-0e089e5ec13d
parent_step_id: 63a93b87-8082-48af-9d09-0e089e5ec13d
previous_result_condition: '{"63a93b87-8082-48af-9d09-0e089e5ec13d": "2"}'
instance_name: Output_3
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
