identifier: c607fb08-febf-426d-a375-d43a88fbf7ce
original_step_id: c607fb08-febf-426d-a375-d43a88fbf7ce
parent_step_ids:
- e79e1692-1e98-4e54-ae81-887cdb5f6ace
parent_step_id: e79e1692-1e98-4e54-ae81-887cdb5f6ace
previous_result_condition: '{"e79e1692-1e98-4e54-ae81-887cdb5f6ace": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
