identifier: 16e0515a-24ec-4af4-8900-421a02d464d9
is_enable: true
version: '0'
name: AWS Instance Containment
description: This block allows you to stop EC2 instances that were identified in the
    alert as potentially compromised or suspicious, supporting the containment phase
    of the incident response process.It uses a boolean input to control manual or
    automatic execution and returns the containment result, false on failure, or an
    empty value if no action is taken.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
modified_by: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
execution_scope: 0
original_playbook_identifier: 16e0515a-24ec-4af4-8900-421a02d464d9
creation_time_unix_time_in_ms: 1782888360960
modification_time_unix_time_in_ms: 1782888360960
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
