-   description: This block allows you to stop EC2 instances that were identified
        in the alert as potentially compromised or suspicious, supporting the containment
        phase of the incident response process.It uses a boolean input to control
        manual or automatic execution and returns the containment result, false on
        failure, or an empty value if no action is taken.
    version: '0'
    item_name: AWS Instance Containment
    item_type: Block
    publish_time: 1782888360
    ticket_number: ''
