identifier: 9306b778-305e-4f05-bc83-316bddf6d526
original_step_id: 9306b778-305e-4f05-bc83-316bddf6d526
parent_step_ids:
- 5d15ef8b-862c-4c89-ac63-d7b711c324de
- 0421194c-096d-4452-b9aa-857a8422aaee
parent_step_id: 5d15ef8b-862c-4c89-ac63-d7b711c324de
previous_result_condition: '{"5d15ef8b-862c-4c89-ac63-d7b711c324de": "", "0421194c-096d-4452-b9aa-857a8422aaee":
    "2"}'
instance_name: AWS User Filter
is_automatic: true
name: Entity Selection
is_skippable: false
description: Creates a group of entities that can be used in other actions. Use conditions
    to fine tune the group.
action_provider: Flow
action_name: EntitySelection
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: ConditionOperator
    value: '0'
-   step_id: null
    playbook_id: null
    name: Conditions
    value: '[{"FieldName":"Entity.Identifier","Operator":1,"Value":"ARN:AWS:IAM","Type":2}]'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
