identifier: c762e18a-ff1b-4ca0-8006-7c246c139501
original_step_id: c762e18a-ff1b-4ca0-8006-7c246c139501
instance_name: AWSIAM_Disable User Access_1
is_automatic: true
name: AWSIAM_Disable User Access
is_skippable: false
description: Disable User Access in AWS by adding an explicit deny inline policy.
    Action works with SOAR User entity type.
action_provider: Scripts
action_name: AWSIAM_Disable User Access
integration: AWSIAM
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: AWSIAM_Disable User Access
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: AWS User Filter.SelectedEntities
parallel_actions: []
step_debug_data: null
