identifier: c31e7e63-dfc8-4d0f-b6e4-70f0f260d2f5
original_step_id: c31e7e63-dfc8-4d0f-b6e4-70f0f260d2f5
parent_step_ids:
- 1c4acf16-f5e2-45af-b2c9-e960edc66cfb
parent_step_id: 1c4acf16-f5e2-45af-b2c9-e960edc66cfb
previous_result_condition: '{"1c4acf16-f5e2-45af-b2c9-e960edc66cfb": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
