identifier: d507ed7c-973e-45bc-a80d-1201363f4127
original_step_id: d507ed7c-973e-45bc-a80d-1201363f4127
parent_step_ids:
- c762e18a-ff1b-4ca0-8006-7c246c139501
parent_step_id: c762e18a-ff1b-4ca0-8006-7c246c139501
previous_result_condition: '{"c762e18a-ff1b-4ca0-8006-7c246c139501": ""}'
instance_name: USER_REMEDIATION_SUMMARY_APRPOVE
is_automatic: true
name: Tools_Set Context Value
is_skippable: false
description: The action sets a key and value in a specific context (alert or case)
action_provider: Scripts
action_name: Tools_Set Context Value
integration: Tools
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Set Context Value
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Value":"[Alert.REMEDIATION]<sep>During the investigation of the alert,
        it was decided to disable the following user accounts:[AWS User Filter.SelectedEntities]","Key":"REMEDIATION","Scope":"Alert"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All users
parallel_actions: []
step_debug_data: null
