identifier: 4de33f5f-73f0-4a7f-8af4-35a52a3bfd82
is_enable: true
version: '0'
name: AWS Enrichment
description: This block retrieves EC2 instance data associated with the case and provides
    context for other actions or analysis.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- '*'
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: Siemplify automation
execution_scope: 0
original_playbook_identifier: 4de33f5f-73f0-4a7f-8af4-35a52a3bfd82
creation_time_unix_time_in_ms: 1783492087203
modification_time_unix_time_in_ms: 1783582614548
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
