identifier: ca197ca6-93a3-4b2d-a0ad-c2c7d327032a
is_enable: true
version: '0'
name: GTI Enrichment
description: This block enhances case entities with Google Threat Intelligence enrichment
    information. Works for IPs, URLs, hostnames, domains, hashes (MD5, SHA-1, SHA-256),
    threat actors, and CVEs.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
modified_by: 9e1cb0e4-a750-431a-b413-a7f76a8b62d7
execution_scope: 0
original_playbook_identifier: ca197ca6-93a3-4b2d-a0ad-c2c7d327032a
creation_time_unix_time_in_ms: 1782888411511
modification_time_unix_time_in_ms: 1782888411511
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
