identifier: fd29a2e6-da7b-4290-a918-e6037f1d83c5
original_step_id: fd29a2e6-da7b-4290-a918-e6037f1d83c5
parent_step_ids:
- 4f709eee-a9d5-4937-a516-c2d6d1f59c27
parent_step_id: 4f709eee-a9d5-4937-a516-c2d6d1f59c27
previous_result_condition: '{"4f709eee-a9d5-4937-a516-c2d6d1f59c27": ""}'
instance_name: Alert Overview
is_automatic: true
name: GoogleChronicle_Get Detection Details
is_skippable: false
description: Fetch information about a detection in Google Chronicle.
action_provider: Scripts
action_name: GoogleChronicle_Get Detection Details
integration: GoogleChronicle
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleChronicle_Get Detection Details
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Rule ID":"[Event.detection_1_ruleId]","Detection ID":"[Event.id]"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
