identifier: 1f2b36b3-a755-4eda-ae52-578c93c5af5e
original_step_id: 1f2b36b3-a755-4eda-ae52-578c93c5af5e
parent_step_ids:
- 7439e254-dfb6-489f-8a62-dd474baac7b3
parent_step_id: 7439e254-dfb6-489f-8a62-dd474baac7b3
previous_result_condition: '{"7439e254-dfb6-489f-8a62-dd474baac7b3": ""}'
instance_name: ALERT PRIORITY
is_automatic: true
name: Alert Priority
is_skippable: false
description: This block sets the alert priority using a previously defined playbook
    variable, ensuring consistent prioritization logic for the case workflow.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: d3f32f73-7261-40f6-bbfd-7f2fb8d6119a
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"10ae184c-258c-40bc-beec-76b7a863fc70","integration":"Siemplify","actionName":"Siemplify_Change
        Case Stage","instanceName":"Case Stage Investigation","stepType":0},{"identifier":"2095288f-ef0a-4882-a45f-60386cf2400e","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"CRITICAL","stepType":0},{"identifier":"4f7a9bc4-cd28-44da-a453-f0325ed99c13","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"RISKY - Update Alert Summary 2","stepType":0},{"identifier":"6cd293b0-01f5-4c1f-af1e-a8800068db45","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"LOW  ","stepType":0},{"identifier":"6fb286f5-c8ff-4ee4-a6ec-c7e7f8f47588","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"HIGH ","stepType":0},{"identifier":"82dfa1bc-070a-401c-8a2b-469a1b2d5d8a","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"MEDIUM","stepType":0},{"identifier":"a2e5d693-c58a-44d4-8f2e-c579bfcadfd7","integration":"Siemplify","actionName":"Siemplify_Change
        Alert Priority","instanceName":"INFORMATIONAL","stepType":0},{"identifier":"c26faa61-cdda-4800-b6b7-69c263806866","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Inconclusive - Update Alert Summary","stepType":0},{"identifier":"d69004d2-f6c9-4dca-b320-20063add8392","integration":"Siemplify","actionName":"Siemplify_Raise
        Incident","instanceName":"Raise Incident","stepType":0},{"identifier":"ffd91397-9b47-4dd0-8ddb-191e550c52bc","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Assign
        Priority","stepType":4}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
