identifier: 13e1729c-08eb-4e08-81cc-26782a8a8535
original_step_id: 13e1729c-08eb-4e08-81cc-26782a8a8535
parent_step_ids:
- fd29a2e6-da7b-4290-a918-e6037f1d83c5
parent_step_id: fd29a2e6-da7b-4290-a918-e6037f1d83c5
previous_result_condition: '{"fd29a2e6-da7b-4290-a918-e6037f1d83c5": ""}'
instance_name: High Risk Users Check_1
is_automatic: true
name: High Risk Users Check
is_skippable: false
description: This block checks Google GTI sourced alerts against a SOAR custom list
    to find matches of targeted Industries.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 9dd19b10-857a-45dd-bde6-c807429fb210
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"28167e6c-e7c7-4f20-bf42-7469b932fdc0","integration":"Tools","actionName":"Tools_Add
        Alert Scoring Information","instanceName":"Add High Severity Record","stepType":0},{"identifier":"4e645219-1c4e-4621-a72b-ba81fb56fae6","integration":"Lists","actionName":"Lists_Search
        Environment Custom Lists","instanceName":"Retrieve Relevant Users","stepType":0},{"identifier":"95436ee0-7ba4-4aa0-919d-419213f35d39","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Are
        there Matches","stepType":4},{"identifier":"d7dfba4e-8b82-4d09-bd02-51dfba4cdf0d","integration":"TemplateEngine","actionName":"TemplateEngine_Render
        Template","instanceName":"Find Matches","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
