identifier: 4c82eeb3-8abe-44ae-8107-e948eb1689bf
original_step_id: 4c82eeb3-8abe-44ae-8107-e948eb1689bf
parent_step_ids:
- 5a7a038d-4028-4cfb-bcc2-b831ad883caa
parent_step_id: 5a7a038d-4028-4cfb-bcc2-b831ad883caa
previous_result_condition: '{"5a7a038d-4028-4cfb-bcc2-b831ad883caa": ""}'
instance_name: Microsoft Defender For Endpoint Containment
is_automatic: true
name: Microsoft Defender For Endpoint Containment
is_skippable: false
description: ' This block allows the playbook to create an isolate machine task in
    Microsoft Defender for Endpoint, helping to contain affected systems and prevent
    further network communication.'
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: a743e4e3-a644-45f5-80cb-1d751e08d581
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"0debfc7c-0550-42fe-9be4-e043e22cf97e","integration":"Flow","actionName":"MultiChoiceQuestion","instanceName":"Isolate
        Machines?","stepType":1},{"identifier":"2bb99a51-2425-4623-bd22-60669cb2082e","integration":"Flow","actionName":"EntitySelection","instanceName":"Hostnames
        and Ips","stepType":0},{"identifier":"58e5a243-fb57-4f6b-8422-8e54f7903f4e","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"COMPUTE_INSTANCE_REMEDIATION_SUMMARY ","stepType":0},{"identifier":"595509ca-b67f-4509-ae72-7bc9aa3ff005","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Count
        Entities In Scope","instanceName":"Count Instances","stepType":0},{"identifier":"62ef9439-8bd8-4725-be39-c2f204394727","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"NO_COMPUTE_INSTANCE_REMEDIATION_SUMMARY","stepType":0},{"identifier":"6d71f876-68fd-4c3c-9edf-ce1b5345b71c","integration":"MicrosoftDefenderATP","actionName":"MicrosoftDefenderATP_Create
        Isolate Machine Task","instanceName":"Isolate Machine","stepType":0},{"identifier":"92e57735-bb82-46fd-8d09-cdf37438f6f6","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Machine
        Isolated","stepType":4},{"identifier":"95013b62-e98b-4e1f-8eb2-3a1683a9b394","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Init
        Remediation Variable","stepType":4},{"identifier":"981ac08e-c253-44b1-9274-c3c125334792","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Has
        instances or local ips?","stepType":4},{"identifier":"c64dfce9-2e05-4b64-80f6-d57f033e003a","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Count
        Entities In Scope","instanceName":"Count Local IPs","stepType":0},{"identifier":"ce332b7f-d3d6-4258-a20c-f3c7858a7e84","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Init Remediation","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
