identifier: 7439e254-dfb6-489f-8a62-dd474baac7b3
original_step_id: 7439e254-dfb6-489f-8a62-dd474baac7b3
parent_step_ids:
- 09b6670d-ec38-40ed-8cfa-11df5b467d9b
parent_step_id: 09b6670d-ec38-40ed-8cfa-11df5b467d9b
previous_result_condition: '{"09b6670d-ec38-40ed-8cfa-11df5b467d9b": ""}'
instance_name: MITRE Enrichment
is_automatic: true
name: MITRE Enrichment
is_skippable: false
description: This block retrieves detailed information about MITRE ATT&CK techniques
    and their associated mitigations, providing valuable context to understand adversary
    behaviors and possible defensive actions.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 09f44d0f-3b17-4482-a986-f87e91d2356c
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"44b5c4a0-d03e-4745-8149-a6936cce611f","integration":"MitreAttck","actionName":"MitreAttck_Get
        Techniques Details","instanceName":"Mitre Techniques Details","stepType":0},{"identifier":"e835198b-aab5-40ad-a774-28b2f5021894","integration":"MitreAttck","actionName":"MitreAttck_Get
        Techniques Mitigations","instanceName":"Mitre Techniques Mitigations","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
