identifier: 8a8648e3-e5a3-4f40-9ff2-101636f6371a
original_step_id: 8a8648e3-e5a3-4f40-9ff2-101636f6371a
parent_step_ids:
- 6fb9d413-825f-4363-8dea-86a99d22e290
parent_step_id: 6fb9d413-825f-4363-8dea-86a99d22e290
previous_result_condition: '{"6fb9d413-825f-4363-8dea-86a99d22e290": ""}'
instance_name: Set Initial Severity
is_automatic: true
name: Set Initial Severity
is_skippable: false
description: This block sets the initial alert score based on the SIEM detection severity
    or the rule metadata severity label.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: fed9062f-e91d-42e7-b0b3-3655904f5eb6
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"0fd38efc-d6e3-4dc7-8d4c-0ffd7dba7e87","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +50","stepType":0},{"identifier":"11603f2a-833f-48f8-8a64-91fc447984b7","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Fallback","stepType":0},{"identifier":"37f5ac42-792c-45b0-b8f6-5c615d0ec90a","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        by alert severity ","stepType":4},{"identifier":"87436da0-bdbb-4f12-a753-acfd4e1ec785","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +90","stepType":0},{"identifier":"a2a18f2e-ae0f-4134-bd18-6aa262963a18","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Initi Summary","stepType":0},{"identifier":"ad9f304c-7860-4687-9bc8-5cd9db66fba8","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +25","stepType":0},{"identifier":"f2b37177-60f5-46bd-b576-001003c41196","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +75","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
