identifier: eb9fa67a-6708-4476-89e0-51744fa92ff7
original_step_id: eb9fa67a-6708-4476-89e0-51744fa92ff7
parent_step_ids:
- 95436ee0-7ba4-4aa0-919d-419213f35d39
parent_step_id: 95436ee0-7ba4-4aa0-919d-419213f35d39
previous_result_condition: '{"95436ee0-7ba4-4aa0-919d-419213f35d39": "2"}'
instance_name: Output_3
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
