identifier: e8ab460a-25b6-4815-b8c7-a7c8e96a15c6
original_step_id: e8ab460a-25b6-4815-b8c7-a7c8e96a15c6
parent_step_ids:
- 28167e6c-e7c7-4f20-bf42-7469b932fdc0
parent_step_id: 28167e6c-e7c7-4f20-bf42-7469b932fdc0
previous_result_condition: '{"28167e6c-e7c7-4f20-bf42-7469b932fdc0": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
