identifier: 3fe28370-4e01-4530-a484-22a017ed7c33
original_step_id: 3fe28370-4e01-4530-a484-22a017ed7c33
parent_step_ids:
- 08d3890f-09dc-4268-9456-d80a59c8bd80
parent_step_id: 08d3890f-09dc-4268-9456-d80a59c8bd80
previous_result_condition: '{"08d3890f-09dc-4268-9456-d80a59c8bd80": ""}'
instance_name: Close Alert
is_automatic: false
name: Siemplify_Close Alert
is_skippable: false
description: Closes the current alert
action_provider: Scripts
action_name: Siemplify_Close Alert
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Close Alert
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Reason":"Malicious","Root Cause":"External attack","Comment":"Write
        here....","Assign To User":"","Tags":""}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
