identifier: 02ae9f6e-c781-44c8-8732-6ce6163d7aaa
original_step_id: 02ae9f6e-c781-44c8-8732-6ce6163d7aaa
parent_step_ids:
- 2796b282-7365-4b6f-b172-2ceaf89effa0
parent_step_id: 2796b282-7365-4b6f-b172-2ceaf89effa0
previous_result_condition: '{"2796b282-7365-4b6f-b172-2ceaf89effa0": ""}'
instance_name: Get Detection Details
is_automatic: true
name: GoogleChronicle_Get Detection Details
is_skippable: false
description: Fetch information about a detection in Google Chronicle.
action_provider: Scripts
action_name: GoogleChronicle_Get Detection Details
integration: GoogleChronicle
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleChronicle_Get Detection Details
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Rule ID":"[Event.detection_1_ruleId]","Detection ID":"[Event.id]"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
