identifier: ad7bd69f-3244-4aa5-95cc-edf53b37b3f4
original_step_id: ad7bd69f-3244-4aa5-95cc-edf53b37b3f4
parent_step_ids:
- 4a8c7351-bd63-4a7a-9a62-e17d65f9faad
parent_step_id: 4a8c7351-bd63-4a7a-9a62-e17d65f9faad
previous_result_condition: '{"4a8c7351-bd63-4a7a-9a62-e17d65f9faad": ""}'
instance_name: Google Workspace Enrichment
is_automatic: true
name: Google Workspace Enrichment
is_skippable: false
description: This block enriches user entities with relevant information from Google
    Workspace, providing additional context to support investigation and response
    activities.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 656628eb-7478-497e-86ab-5b103aca9e2d
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"d1b25680-ba66-42f7-977e-3b316a3a151d","integration":"GSuite","actionName":"GSuite_Enrich
        Entities","instanceName":"Google Workspace Enrichment","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
