identifier: 4a8c7351-bd63-4a7a-9a62-e17d65f9faad
original_step_id: 4a8c7351-bd63-4a7a-9a62-e17d65f9faad
parent_step_ids:
- abcb8b55-0251-4805-af6f-ca6f565c8931
parent_step_id: abcb8b55-0251-4805-af6f-ca6f565c8931
previous_result_condition: '{"abcb8b55-0251-4805-af6f-ca6f565c8931": ""}'
instance_name: Google SecOps Enrichment
is_automatic: true
name: Google SecOps Enrichment
is_skippable: false
description: This block retrieves relevant details about users and assets involved
    in the case, enhancing the context available for analysis and subsequent actions
    within Google SecOps SOAR.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 9b1134a9-b60c-4fcd-9c25-c173f73cf4d9
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"07be63e9-9f02-44f5-9260-66515720d179","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User and Email Query","stepType":0},{"identifier":"0dab9714-7b99-4bbc-89c7-c349f1ac8e78","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User Query","stepType":0},{"identifier":"51f1ba5c-aafd-433f-a157-a872a488cdd2","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary URLs Entity Selection","stepType":0},{"identifier":"61cf47fc-e223-41ae-a449-d3996e7c0d1a","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary Domains","stepType":0},{"identifier":"6c8c885f-779e-4174-9adc-1119226b3e81","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails","stepType":0},{"identifier":"747daaff-ced1-4d78-8c4f-f2f8034626d7","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"User Activity","stepType":0},{"identifier":"765803d9-3df8-45e8-92cb-5a6f502aa774","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        User Query based on Param","stepType":4},{"identifier":"8764b205-83d4-4ae3-a0fc-8cc4ab3cffd5","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Emails Query","stepType":0},{"identifier":"9827c5d6-6c34-498b-81a6-24400a3dff12","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails 2","stepType":0},{"identifier":"a412d1e9-b3d9-44f2-91b6-d8365fecf91e","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Has
        Target Resource?","stepType":4},{"identifier":"b0aa538c-ceb0-40a5-99b0-c0ce62f145fd","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"Target Resource Activity","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
