identifier: 6f54bac1-76eb-48e4-a0d7-314cb9950b3f
original_step_id: 6f54bac1-76eb-48e4-a0d7-314cb9950b3f
parent_step_ids:
- ad7bd69f-3244-4aa5-95cc-edf53b37b3f4
parent_step_id: ad7bd69f-3244-4aa5-95cc-edf53b37b3f4
previous_result_condition: '{"ad7bd69f-3244-4aa5-95cc-edf53b37b3f4": ""}'
instance_name: Google Workspace Containment
is_automatic: true
name: Google Workspace Containment
is_skippable: false
description: This block allows the playbook to update Google Workspace Directory user
    accounts as part of containment or response actions, supporting account management
    and security controls.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 22b1100c-b12e-4bfd-b7eb-318aa5eff71a
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"1258f471-a95e-4ae2-9391-f579e9ecc941","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Init Remediation","stepType":0},{"identifier":"2f922206-0091-4986-84de-60c22e1bd0a0","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Init
        Remediation Variable","stepType":4},{"identifier":"617c391e-fb3b-4cbc-af31-5f50f7d13117","integration":"Flow","actionName":"MultiChoiceQuestion","instanceName":"Update
        User?","stepType":1},{"identifier":"61c1e4e4-8f73-42bd-a496-000cbe1be7ad","integration":"Flow","actionName":"IfFlowCondition","instanceName":"User
        exists?","stepType":4},{"identifier":"68400b4e-3616-48e0-9bc2-88d071be8596","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"REMEDIATION No Users to update","stepType":0},{"identifier":"68c7434a-1d1c-4305-a01e-af84779e037d","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"REMEDIATION Update User","stepType":0},{"identifier":"813b4f7f-3729-455c-b1ba-8b505978a624","integration":"GSuite","actionName":"GSuite_List
        Users","instanceName":"List Users","stepType":0},{"identifier":"ed362eae-e9ba-4e8b-87e2-0cc8a9770e45","integration":"Flow","actionName":"EntitySelection","instanceName":"Filter
        Principal User","stepType":0},{"identifier":"ed7daa7b-2997-465f-8855-2cd37690f357","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"REMEDIATION Not Update User","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
