identifier: 2f25f49d-b95c-47e1-93ee-5297a9ef2da7
original_step_id: 2f25f49d-b95c-47e1-93ee-5297a9ef2da7
parent_step_ids:
- dd5d9ad2-fd90-4d6d-960c-49f36c99a165
parent_step_id: dd5d9ad2-fd90-4d6d-960c-49f36c99a165
previous_result_condition: '{"dd5d9ad2-fd90-4d6d-960c-49f36c99a165": ""}'
instance_name: Set Initial Severity
is_automatic: true
name: Set Initial Severity
is_skippable: false
description: This block sets the initial alert score based on the SIEM detection severity
    or the rule metadata severity label.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 2bd47c2c-8ad7-4cd3-889b-74b21d5912e2
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"1cfb4d01-9903-42d5-8b8c-c20deb7070ca","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +90","stepType":0},{"identifier":"444f7f33-9135-4679-9563-ab8e0d53c4fa","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +75","stepType":0},{"identifier":"74bc355f-4e74-4cda-b178-22d39bc89349","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Fallback","stepType":0},{"identifier":"a297a916-6d4d-4a64-af86-43e914ae9165","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +50","stepType":0},{"identifier":"aaf8b445-d430-49b9-bb86-5d935633969a","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        by alert severity ","stepType":4},{"identifier":"b8cb7ae1-1a1b-47af-b634-b0d664395d61","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Initi Summary","stepType":0},{"identifier":"cbf99b5c-5523-49e0-90dc-a2cc6d821355","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Set Initial Priority +25","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
