identifier: c3820dc5-fd9d-48a8-92f4-364b8dfba842
original_step_id: c3820dc5-fd9d-48a8-92f4-364b8dfba842
parent_step_ids:
- 3d56f2fc-f550-4c34-a758-edece16841b3
parent_step_id: 3d56f2fc-f550-4c34-a758-edece16841b3
previous_result_condition: '{"3d56f2fc-f550-4c34-a758-edece16841b3": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
