identifier: d43bde93-2aa6-4669-91ff-6e234eb06af5
original_step_id: d43bde93-2aa6-4669-91ff-6e234eb06af5
parent_step_ids:
- 029a011a-a1c8-4133-a93d-a3afc4f4d1c5
parent_step_id: 029a011a-a1c8-4133-a93d-a3afc4f4d1c5
previous_result_condition: '{"029a011a-a1c8-4133-a93d-a3afc4f4d1c5": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
