identifier: 24e15b68-0a4a-4fc0-b84c-67ae5ae4a2b4
original_step_id: 24e15b68-0a4a-4fc0-b84c-67ae5ae4a2b4
parent_step_ids:
- e65cd912-30b1-4c2e-85ab-5d2a168d1cb9
parent_step_id: e65cd912-30b1-4c2e-85ab-5d2a168d1cb9
previous_result_condition: '{"e65cd912-30b1-4c2e-85ab-5d2a168d1cb9": "2"}'
instance_name: Output_3
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
