identifier: cdb700f2-ac47-4c79-ba19-1591e8d98f84
is_enable: true
version: '0'
name: Microsoft Defender For Endpoint Enrichment - 1
description: This block enriches Microsoft Defender for Endpoint hosts by retrieving
    relevant data such as logged-on users, file-related alerts, and machine-related
    alerts. It also supports file enrichment using SHA1 hashes, providing additional
    context to assist investigation and response activities.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: Siemplify automation
execution_scope: 0
original_playbook_identifier: cdb700f2-ac47-4c79-ba19-1591e8d98f84
creation_time_unix_time_in_ms: 1783492156751
modification_time_unix_time_in_ms: 1783582648817
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
