identifier: a6467971-614c-449a-8f7b-d1bae50cd1f3
original_step_id: a6467971-614c-449a-8f7b-d1bae50cd1f3
parent_step_ids:
- ff7d767a-2ed3-4c9d-ac8d-0a4bf143430c
- 37914919-0d70-4b23-b595-e060d0f03111
parent_step_id: ff7d767a-2ed3-4c9d-ac8d-0a4bf143430c
previous_result_condition: '{"ff7d767a-2ed3-4c9d-ac8d-0a4bf143430c": "", "37914919-0d70-4b23-b595-e060d0f03111":
    "4"}'
instance_name: Has Target Resource?
is_automatic: true
name: Condition
is_skippable: false
description: This condition determines the progress of the playbook. Conditions are
    built based on cases data (cases, alerts, vents, entities and environment properties)
    as-well as data that comes back from previous playbook steps.
action_provider: Flow
action_name: IfFlowCondition
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: condition
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: Branches
    value: '[{"LogicalOperator":0,"Conditions":[{"Operator":8,"FieldName":"[Event.event_target_resource_name]","Type":2,"Value":"","CustomOperatorName":null}],"Order":1,"IsDefaultBranch":false,"Name":"Yes"},{"LogicalOperator":0,"Conditions":[],"Order":2,"IsDefaultBranch":true,"Name":"Branch"}]'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: ErrorFallbackBranch
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
