identifier: e357601c-2c74-4e69-a92a-a20857a3b56d
original_step_id: e357601c-2c74-4e69-a92a-a20857a3b56d
parent_step_ids:
- a6467971-614c-449a-8f7b-d1bae50cd1f3
parent_step_id: a6467971-614c-449a-8f7b-d1bae50cd1f3
previous_result_condition: '{"a6467971-614c-449a-8f7b-d1bae50cd1f3": "2"}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
