identifier: 9d4df304-1b05-46b6-9067-1503107972e7
is_enable: true
version: '0'
name: Azure Containment - 1
description: This block allows the playbook to apply containment actions to Azure
    user accounts by either updating the password or disabling the account. It also
    provides the option to ignore the action and take no changes when required.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: Siemplify automation
execution_scope: 0
original_playbook_identifier: 9d4df304-1b05-46b6-9067-1503107972e7
creation_time_unix_time_in_ms: 1783492146517
modification_time_unix_time_in_ms: 1783582588623
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
