identifier: 0e06b0d0-87d2-4903-9093-24742ceab70a
is_enable: true
version: '0'
name: Azure Enrichment
description: This block enriches Siemplify Host and User entities with relevant information
    from Azure Active Directory, providing additional context to support investigation
    and response activities.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- Default Environment
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: 6900fc46-2900-40ab-9d7c-479966cd22ec
execution_scope: 0
original_playbook_identifier: 0e06b0d0-87d2-4903-9093-24742ceab70a
creation_time_unix_time_in_ms: 1783492131002
modification_time_unix_time_in_ms: 1783492131002
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
