-   description: This block enriches Siemplify Host and User entities with relevant
        information from Azure Active Directory, providing additional context to support
        investigation and response activities.
    version: '0'
    item_name: Azure Enrichment
    item_type: Block
    publish_time: 1783492131
    ticket_number: ''
