identifier: 0a04e1d4-18fb-41ce-bdb0-b28ca5b01e01
original_step_id: 42fea3f5-2add-4922-85a3-2f54237c36bc
parent_step_ids:
- f52d10c0-6c73-49e7-acd7-cc8d99f1e602
parent_step_id: f52d10c0-6c73-49e7-acd7-cc8d99f1e602
previous_result_condition: '{"f52d10c0-6c73-49e7-acd7-cc8d99f1e602": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
