-   description: Google Workspace Starting Playbook provides reference implementation
        of how Google Workspace alerts can be processed in Google SecOps.
    version: '0'
    item_name: Google Workspace Starting Playbook
    item_type: Playbook
    publish_time: 1783582665
    ticket_number: ''
