identifier: 1069f4f2-3d76-4141-ad73-5f55921c3dec
original_step_id: 1069f4f2-3d76-4141-ad73-5f55921c3dec
parent_step_ids:
- 1091d8df-2847-4a78-9965-623a72768589
parent_step_id: 1091d8df-2847-4a78-9965-623a72768589
previous_result_condition: '{"1091d8df-2847-4a78-9965-623a72768589": ""}'
instance_name: Close Alert
is_automatic: false
name: Siemplify_Close Alert
is_skippable: false
description: Closes the current alert
action_provider: Scripts
action_name: Siemplify_Close Alert
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Close Alert
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Reason":"Malicious","Root Cause":"External attack","Comment":"Write
        here ...","Assign To User":"","Tags":""}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
