identifier: 1091d8df-2847-4a78-9965-623a72768589
original_step_id: 1091d8df-2847-4a78-9965-623a72768589
parent_step_ids:
- 08597b3c-fbcf-4275-a14f-c1846a9de4aa
parent_step_id: 08597b3c-fbcf-4275-a14f-c1846a9de4aa
previous_result_condition: '{"08597b3c-fbcf-4275-a14f-c1846a9de4aa": ""}'
instance_name: CrowdStrike Containment
is_automatic: true
name: CrowdStrike Containment
is_skippable: false
description: This block allows the playbook to perform containment actions on endpoints
    by targeting the IPs and hostnames associated with the case, helping to prevent
    further compromise during incident response.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 4abd46d3-30ba-45ea-a31e-99bb0c5e430e
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[{"FieldName":"EntityName","Value":"[CrowdStrikeFalcon Host Information.JsonResult|
        \"Entity\"]"}]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"33ffb710-9304-4cb2-88c2-39dfeb3d454b","integration":"CrowdStrikeFalcon","actionName":"CrowdStrikeFalcon_Contain
        Endpoint","instanceName":"Contain Endpoint","stepType":0},{"identifier":"8c6831d5-124e-4b6e-87a5-04c635031bcb","integration":"Flow","actionName":"MultiChoiceQuestion","instanceName":"Proceed
        to Remediation : Isolate Host","stepType":1},{"identifier":"feae62ef-bd06-4ebf-bbb0-cd7a44c37d63","integration":"Flow","actionName":"EntitySelection","instanceName":"Hostnames
        and IPs","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
