identifier: caa4b982-a673-4560-935d-732ed63a7420
original_step_id: caa4b982-a673-4560-935d-732ed63a7420
parent_step_ids:
- d60848ec-6d05-48c0-8dd1-35ac85c17fcd
parent_step_id: d60848ec-6d05-48c0-8dd1-35ac85c17fcd
previous_result_condition: '{"d60848ec-6d05-48c0-8dd1-35ac85c17fcd": ""}'
instance_name: EDR Tag
is_automatic: true
name: Siemplify_Case Tag
is_skippable: false
description: Add given tag to the case the current alert is grouped to
action_provider: Scripts
action_name: Siemplify_Case Tag
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Case Tag
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Tag":"EDR"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
