identifier: de07e9a8-b2ba-400a-a1f9-151a4a41849f
original_step_id: de07e9a8-b2ba-400a-a1f9-151a4a41849f
parent_step_ids:
- f9ea85fc-3b67-4470-8775-6a06fade3560
parent_step_id: f9ea85fc-3b67-4470-8775-6a06fade3560
previous_result_condition: '{"f9ea85fc-3b67-4470-8775-6a06fade3560": ""}'
instance_name: GoogleSecops Enrichment
is_automatic: true
name: Google SecOps Enrichment
is_skippable: false
description: This block retrieves relevant details about users and assets involved
    in the case, enhancing the context available for analysis and subsequent actions
    within Google SecOps SOAR.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 596300ca-d221-412e-a2f1-0e500021cf04
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"01535f36-7c47-49ca-8a4f-83d3b940bbfb","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"Emails Query","stepType":0},{"identifier":"1caf4897-2481-4ec4-ae34-1975e613048e","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Has
        Target Resource?","stepType":4},{"identifier":"204bd686-ca14-43b1-a29e-4070395046fa","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User and Email Query","stepType":0},{"identifier":"3ebe4239-1cba-435c-ae3d-e6459c865082","integration":"Siemplify","actionName":"Siemplify_Set
        Scope Context Value","instanceName":"User Query","stepType":0},{"identifier":"42e9ae84-aaeb-480b-9a93-e1d0b2ebeac5","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails","stepType":0},{"identifier":"8b5a1e50-171f-4409-a8ed-2c9ece5b0ce5","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Query
        Joiner","instanceName":"Join Emails 2","stepType":0},{"identifier":"9dcc4bc8-964f-4b28-a187-75c76eee3b95","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary URLs Entity Selection","stepType":0},{"identifier":"c28ae7ff-9185-4bda-82ee-4d5226c4abf8","integration":"Flow","actionName":"EntitySelection","instanceName":"Ignore
        Unnecessary Domains","stepType":0},{"identifier":"e9f839cc-1bd7-436e-8d50-64438a226ffc","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"User Activity","stepType":0},{"identifier":"f420dd11-e152-4eb0-aa42-aa1d14eaf290","integration":"GoogleChronicle","actionName":"GoogleChronicle_Execute
        UDM Query","instanceName":"Target Resource Activity","stepType":0},{"identifier":"fee996dc-55b5-4f7c-b2f5-1a9517501563","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Set
        User Query based on Param","stepType":4}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
