identifier: a5de2f96-a52b-44a9-882d-dd712eed81da
original_step_id: a5de2f96-a52b-44a9-882d-dd712eed81da
parent_step_ids:
- 31eabec7-a2cc-460a-8c21-13969e531942
parent_step_id: 31eabec7-a2cc-460a-8c21-13969e531942
previous_result_condition: '{"31eabec7-a2cc-460a-8c21-13969e531942": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
