identifier: 4d58e0f3-007b-48c2-85f4-2ea67f75c99e
original_step_id: d4116b8b-18a9-4eaa-81f6-4da3f2b4c1ee
parent_step_ids:
- 5efb0efb-ea0c-4766-b780-07bda664eed5
parent_step_id: 5efb0efb-ea0c-4766-b780-07bda664eed5
previous_result_condition: '{"5efb0efb-ea0c-4766-b780-07bda664eed5": ""}'
instance_name: AWSEC2 Stop Instance
is_automatic: true
name: AWSEC2_Stop Instance
is_skippable: false
description: Stop an Amazon EBS-backed instance. When you stop an instance, we attempt
    to shut it down forcibly after a short while. It can take a few minutes for the
    instance to stop. The instance can be started at any time. Notice that you can't
    stop an instance store-backed instance.  For more information about instance store-backed
    instances, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ComponentsAMIs.html#storage-for-the-root-device
action_provider: Scripts
action_name: AWSEC2_Stop Instance
integration: AWSEC2
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: AWSEC2_Stop Instance
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Instance IDs":"[Instance Ids.ScriptResult]","Force":true}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: AWS EC2 Filter.SelectedEntities
parallel_actions: []
step_debug_data: null
