identifier: 8bd0316b-a0f7-4f26-be8f-72e5418d91d8
original_step_id: a34fbb69-d409-4008-a3a2-e20b75ec5ae6
parent_step_ids:
- 80493f4c-0c45-4a4f-9ad4-36bc8a6dab84
parent_step_id: 80493f4c-0c45-4a4f-9ad4-36bc8a6dab84
previous_result_condition: '{"80493f4c-0c45-4a4f-9ad4-36bc8a6dab84": "1"}'
instance_name: Init Remediation
is_automatic: true
name: Tools_Set Context Value
is_skippable: false
description: The action sets a key and value in a specific context (alert or case)
action_provider: Scripts
action_name: Tools_Set Context Value
integration: Tools
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Set Context Value
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Value":"-1","Key":"REMEDIATION","Scope":"Alert"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
