identifier: e08c4150-f2b6-4537-a09b-4b5e2ec4a0e3
original_step_id: a2f13355-61bb-43d3-902a-eb29d4addafd
parent_step_ids:
- 8ab8d270-dbd6-4a51-9d68-228a1c7fd217
parent_step_id: 8ab8d270-dbd6-4a51-9d68-228a1c7fd217
previous_result_condition: '{"8ab8d270-dbd6-4a51-9d68-228a1c7fd217": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
