-   description: Microsoft Defender for Endpoint Starting Playbook provides reference
        implementation of how Microsoft Defender for Endpoint alerts can be processed
        in Google SecOps.
    version: '0'
    item_name: Microsoft Defender for Endpoint Starting Playbook
    item_type: Playbook
    publish_time: 1783582670
    ticket_number: ''
