identifier: 1aa32f66-7072-49f9-9e8f-737ee33b563d
type_: case_data
logical_operator: or
conditions:
-   field_name: '[Event.event_metadata_logType]'
    value: MICROSOFT_DEFENDER_ENDPOINT
    match_type: equal
    custom_operator_name: null
-   field_name: '[Event.event_metadata_logType]'
    value: MICROSOFT_DEFENDER_ENDPOINT_IOS
    match_type: equal
    custom_operator_name: null
-   field_name: '[Event.event_metadata_logType]'
    value: 'WINDOWS_DEFENDER_ATP

        '
    match_type: equal
    custom_operator_name: null
