identifier: 6daf479d-04f9-4bb3-a651-eb361cf24f74
original_step_id: 6daf479d-04f9-4bb3-a651-eb361cf24f74
parent_step_ids:
- a412d1e9-b3d9-44f2-91b6-d8365fecf91e
parent_step_id: a412d1e9-b3d9-44f2-91b6-d8365fecf91e
previous_result_condition: '{"a412d1e9-b3d9-44f2-91b6-d8365fecf91e": "2"}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
