identifier: 0dab9714-7b99-4bbc-89c7-c349f1ac8e78
original_step_id: 0dab9714-7b99-4bbc-89c7-c349f1ac8e78
parent_step_ids:
- 765803d9-3df8-45e8-92cb-5a6f502aa774
parent_step_id: 765803d9-3df8-45e8-92cb-5a6f502aa774
previous_result_condition: '{"765803d9-3df8-45e8-92cb-5a6f502aa774": "2"}'
instance_name: User Query
is_automatic: true
name: Siemplify_Set Scope Context Value
is_skippable: false
description: 'Action sets a value for a key specified that is stored in the Siemplify
    database. Available scopes to get context values for: Alert, Case, Global. Action
    is not working on Siemplify entities. Note: Key Name parameter is case insensitive.'
action_provider: Scripts
action_name: Siemplify_Set Scope Context Value
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Set Scope Context Value
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Context Scope":"Alert","Key Name":"SIEM_PRINCIPAL_USERS_QUERY","Key
        Value":"principal.user.userid = \"[Event.event_principal_user_userid]\""}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
