identifier: 8a1aafa8-f589-4c50-95bf-3827ef33c057
original_step_id: 8a1aafa8-f589-4c50-95bf-3827ef33c057
parent_step_ids:
- ef22e15e-7a7a-4c60-a698-bcddfe256345
parent_step_id: ef22e15e-7a7a-4c60-a698-bcddfe256345
previous_result_condition: '{"ef22e15e-7a7a-4c60-a698-bcddfe256345": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
