identifier: 94a3bea7-e403-4419-8ad4-f6eab3db39e9
original_step_id: 206814e1-d638-4d92-9af5-5e139b5e1306
parent_step_ids:
- 33ffb710-9304-4cb2-88c2-39dfeb3d454b
parent_step_id: 33ffb710-9304-4cb2-88c2-39dfeb3d454b
previous_result_condition: '{"33ffb710-9304-4cb2-88c2-39dfeb3d454b": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
