identifier: c3d17338-4f31-4050-b0bd-cce860209eb7
original_step_id: f2217b25-d691-4a0e-b5d9-61bb0eeb6325
parent_step_ids:
- 8c6831d5-124e-4b6e-87a5-04c635031bcb
parent_step_id: 8c6831d5-124e-4b6e-87a5-04c635031bcb
previous_result_condition: '{"8c6831d5-124e-4b6e-87a5-04c635031bcb": "2"}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
