identifier: 3809e063-a8d8-4f4f-a37d-f719d366be8c
original_step_id: 3809e063-a8d8-4f4f-a37d-f719d366be8c
parent_step_ids:
- 87d63a65-94a3-4e44-85a5-0415fe7c395f
parent_step_id: 87d63a65-94a3-4e44-85a5-0415fe7c395f
previous_result_condition: '{"87d63a65-94a3-4e44-85a5-0415fe7c395f": "2"}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
