identifier: 1c413688-dc98-42a3-a294-607314ec4ef0
is_enable: true
version: '0'
name: AWS Users Containment
description: An embedded workflow that can receive inputs and return an output.
priority: 2
category_name: Content Hub Playbooks
category: 2
environments:
- '*'
is_debug_mode: false
type: block
creator: 6900fc46-2900-40ab-9d7c-479966cd22ec
modified_by: Siemplify automation
execution_scope: 0
original_playbook_identifier: 1c413688-dc98-42a3-a294-607314ec4ef0
creation_time_unix_time_in_ms: 1783492087611
modification_time_unix_time_in_ms: 1783582655740
template_name: null
debug_data:
    debugBaseAlertId: null
    debugAlertId: null
entity_access_level: 2
default_access_level: 2
permissions: []
overview_templates: []
creation_source: 1
