identifier: c0c6f9b9-02c5-4651-b77d-a6adc13f5a30
original_step_id: c0c6f9b9-02c5-4651-b77d-a6adc13f5a30
parent_step_ids:
- e145dc87-688f-44cf-9470-9fb13c38e82b
parent_step_id: e145dc87-688f-44cf-9470-9fb13c38e82b
previous_result_condition: '{"e145dc87-688f-44cf-9470-9fb13c38e82b": ""}'
instance_name: Find Matches
is_automatic: true
name: TemplateEngine_Render Template
is_skippable: false
description: 'This action will render a Jinja2 template using a JSON input.  '
action_provider: Scripts
action_name: TemplateEngine_Render Template
integration: TemplateEngine
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: TemplateEngine_Render Template
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"JSON Object":"{}","Jinja":"{% set data = ''[Retrieve Relevant Users.JsonResult|
        \"entityIdentifier\"]'' -%}\n{% set result = [] -%}\n{% for entry in data.split('','')
        -%}\n{% if entry in \"[Entity.Identifier]\" -%}\n{% set result = result.append(entry)
        -%}\n{% endif %}\n{% endfor %}\n{{ result | join('','')}}","Include Case Data":false,"Template":"{\"Content\":\"\",\"ContentTemplateName\":\"\",\"HtmlTemplateName\":\"\"}"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All users
parallel_actions: []
step_debug_data: null
