identifier: 5f256bb8-5bc1-4149-a19b-2209bc9f2ffe
original_step_id: 5f256bb8-5bc1-4149-a19b-2209bc9f2ffe
parent_step_ids:
- 591d3101-cedc-4c63-9c2b-b8a22a92e77a
parent_step_id: 591d3101-cedc-4c63-9c2b-b8a22a92e77a
previous_result_condition: '{"591d3101-cedc-4c63-9c2b-b8a22a92e77a": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
