identifier: b015fb6c-efe2-49f4-88e5-dbb9f200b908
original_step_id: b015fb6c-efe2-49f4-88e5-dbb9f200b908
parent_step_ids:
- 19cc7985-cdf5-4697-8cd6-815ea7d130cb
parent_step_id: 19cc7985-cdf5-4697-8cd6-815ea7d130cb
previous_result_condition: '{"19cc7985-cdf5-4697-8cd6-815ea7d130cb": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
