identifier: 6994b115-461c-40e4-a291-0f4904c6a7d2
original_step_id: a81dbeda-1f23-4e7b-a49d-2465e591cfe4
parent_step_ids:
- 5ae322b4-49a1-425c-a2fb-c81518fcfc45
parent_step_id: 5ae322b4-49a1-425c-a2fb-c81518fcfc45
previous_result_condition: '{"5ae322b4-49a1-425c-a2fb-c81518fcfc45": "1"}'
instance_name: Containment Decision
is_automatic: false
name: MultiChoiceQuestion
is_skippable: false
description: This step conditions the progress of the playbook according to a question
    the analyst has to answer manually, would be used most for questions which can't
    be answered automatically
action_provider: Flow
action_name: MultiChoiceQuestion
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: multi_choice_question
parameters:
-   step_id: null
    playbook_id: null
    name: Answers
    value: '{"1":"Reset Password","2":"Disable User","3":"Do Nothing"}'
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: Question
    value: Do you to procede with remediation steps?
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: null
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: 'true'
parallel_actions: []
step_debug_data: null
