identifier: a96a0be8-70b5-42e5-9d3c-e9395e2e7831
original_step_id: 5d619e79-5a71-4daa-a975-581eed7bca2b
parent_step_ids:
- ae15693e-a20c-421c-8b12-56ae8a7087b5
parent_step_id: ae15693e-a20c-421c-8b12-56ae8a7087b5
previous_result_condition: '{"ae15693e-a20c-421c-8b12-56ae8a7087b5": ""}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
