identifier: f0235828-7607-42db-8e0e-95287e265028
original_step_id: 8c7b4e3d-a87f-47ec-ab96-df774cedac9c
parent_step_ids:
- aa476b8f-a3cf-45fd-a505-28737be5b8f6
parent_step_id: aa476b8f-a3cf-45fd-a505-28737be5b8f6
previous_result_condition: '{"aa476b8f-a3cf-45fd-a505-28737be5b8f6": ""}'
instance_name: Output_5
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
