identifier: c4ea3f1a-7ef9-4c1b-94a1-226a22d3ce1f
original_step_id: 00e76ee2-9cc7-4463-b281-54e03ee05638
parent_step_ids:
- 6994b115-461c-40e4-a291-0f4904c6a7d2
parent_step_id: 6994b115-461c-40e4-a291-0f4904c6a7d2
previous_result_condition: '{"6994b115-461c-40e4-a291-0f4904c6a7d2": "1"}'
instance_name: Reset Password
is_automatic: true
name: Okta_Reset Password
is_skippable: false
description: Generate a one-time token that can be used to reset a user's password
action_provider: Scripts
action_name: Okta_Reset Password
integration: Okta
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Okta_Reset Password
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"User IDs Or Logins":"[Event.event_principal_user_emailAddresses]","Send
        Email":true,"Also Run On Scope":false}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: Filter Principal User.SelectedEntities
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: null
parallel_actions: []
step_debug_data: null
