identifier: 0943ed7c-d55d-45ad-b561-70f159fbc1c1
original_step_id: 0943ed7c-d55d-45ad-b561-70f159fbc1c1
parent_step_ids:
- 388b735c-e03f-4bda-8aee-12c30298488d
parent_step_id: 388b735c-e03f-4bda-8aee-12c30298488d
previous_result_condition: '{"388b735c-e03f-4bda-8aee-12c30298488d": ""}'
instance_name: Alert Overview
is_automatic: true
name: GoogleChronicle_Get Detection Details
is_skippable: false
description: Fetch information about a detection in Google Chronicle.
action_provider: Scripts
action_name: GoogleChronicle_Get Detection Details
integration: GoogleChronicle
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: GoogleChronicle_Get Detection Details
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Rule ID":"[Event.detection_1_ruleId]","Detection ID":"[Event.id]"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
