identifier: 7caf68e6-9ca8-44e7-9838-eb739c5659b9
original_step_id: 7caf68e6-9ca8-44e7-9838-eb739c5659b9
parent_step_ids:
- c99542ae-e873-4a21-804e-0acadf59663b
parent_step_id: c99542ae-e873-4a21-804e-0acadf59663b
previous_result_condition: '{"c99542ae-e873-4a21-804e-0acadf59663b": ""}'
instance_name: Change Stage to Assesment
is_automatic: true
name: Siemplify_Change Case Stage
is_skippable: false
description: Change case stage to handling
action_provider: Scripts
action_name: Siemplify_Change Case Stage
integration: Siemplify
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 617bcb53-fa62-407c-a538-7afd8f8c90d1
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Siemplify_Change Case Stage
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Stage":"Assessment"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
