identifier: 62b6c1c8-2f19-499c-8791-18e41402f3de
original_step_id: 62b6c1c8-2f19-499c-8791-18e41402f3de
parent_step_ids:
- af6da985-c729-49d3-8244-330ca74cb74e
- 48734fd3-9190-4729-a1b0-c781f47f3935
parent_step_id: af6da985-c729-49d3-8244-330ca74cb74e
previous_result_condition: '{"af6da985-c729-49d3-8244-330ca74cb74e": "", "48734fd3-9190-4729-a1b0-c781f47f3935":
    "2"}'
instance_name: Change Case Name
is_automatic: true
name: Tools_Change Case Name
is_skippable: false
description: The action changes the case's name (title)
action_provider: Scripts
action_name: Tools_Change Case Name
integration: Tools
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Tools_Change Case Name
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"New Name":"Microsoft Defender for Endpoint Detection : [Event.detection_1_ruleName]","Only
        If First Alert":false}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
