identifier: 56a43b14-40e6-4e59-8a35-ba6214a6ab35
original_step_id: 56a43b14-40e6-4e59-8a35-ba6214a6ab35
parent_step_ids:
- 553dd264-d3f4-42bb-b418-d12c6a184abc
parent_step_id: 553dd264-d3f4-42bb-b418-d12c6a184abc
previous_result_condition: '{"553dd264-d3f4-42bb-b418-d12c6a184abc": ""}'
instance_name: Google Workspace Enrichment
is_automatic: true
name: Google Workspace Enrichment
is_skippable: false
description: This block enriches user entities with relevant information from Google
    Workspace, providing additional context to support investigation and response
    activities.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 206727ae-2e18-43cc-ae12-28892a4bbb65
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"386e9af5-f73e-4678-bba5-dc1245b2b35c","integration":"GSuite","actionName":"GSuite_Enrich
        Entities","instanceName":"Google Workspace Enrichment","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
