identifier: e96ec706-82cc-4bde-8d18-50c684fcfe67
original_step_id: e96ec706-82cc-4bde-8d18-50c684fcfe67
parent_step_ids:
- 0943ed7c-d55d-45ad-b561-70f159fbc1c1
parent_step_id: 0943ed7c-d55d-45ad-b561-70f159fbc1c1
previous_result_condition: '{"0943ed7c-d55d-45ad-b561-70f159fbc1c1": ""}'
instance_name: High Risk Users Check_1
is_automatic: true
name: High Risk Users Check
is_skippable: false
description: This block checks Google GTI sourced alerts against a SOAR custom list
    to find matches of targeted Industries.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: cad61bbe-0b4a-4ada-8128-e92f4e223b27
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"029a011a-a1c8-4133-a93d-a3afc4f4d1c5","integration":"Tools","actionName":"Tools_Add
        Alert Scoring Information","instanceName":"Add High Severity Record","stepType":0},{"identifier":"226b4488-3d77-4845-8e4e-8558268d8c84","integration":"TemplateEngine","actionName":"TemplateEngine_Render
        Template","instanceName":"Find Matches","stepType":0},{"identifier":"7bb47836-7f79-4a53-a3f9-ee362f653341","integration":"Lists","actionName":"Lists_Search
        Environment Custom Lists","instanceName":"Retrieve Relevant Users","stepType":0},{"identifier":"e65cd912-30b1-4c2e-85ab-5d2a168d1cb9","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Are
        there Matches","stepType":4}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
