identifier: 81820b51-fa32-49f8-9189-3c41d745158d
original_step_id: 81820b51-fa32-49f8-9189-3c41d745158d
parent_step_ids:
- 7caf68e6-9ca8-44e7-9838-eb739c5659b9
parent_step_id: 7caf68e6-9ca8-44e7-9838-eb739c5659b9
previous_result_condition: '{"7caf68e6-9ca8-44e7-9838-eb739c5659b9": ""}'
instance_name: Microsoft Defender For Endpoint Containment
is_automatic: true
name: Microsoft Defender For Endpoint Containment
is_skippable: false
description: ' This block allows the playbook to create an isolate machine task in
    Microsoft Defender for Endpoint, helping to contain affected systems and prevent
    further network communication.'
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: f3196a4e-e8c7-4456-81ce-655cae6f91b8
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"24f9fa92-235a-481d-9490-4361425ed7ad","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"NO_COMPUTE_INSTANCE_REMEDIATION_SUMMARY","stepType":0},{"identifier":"5475d50d-116d-409a-9b0b-4d0f8042bf4f","integration":"Flow","actionName":"MultiChoiceQuestion","instanceName":"Isolate
        Machines?","stepType":1},{"identifier":"58413877-dbb0-4baf-bb6c-8d634ea17e96","integration":"Flow","actionName":"EntitySelection","instanceName":"Hostnames
        and Ips","stepType":0},{"identifier":"66e5b3a2-4a1b-4127-a2f5-a3226feb7016","integration":"MicrosoftDefenderATP","actionName":"MicrosoftDefenderATP_Create
        Isolate Machine Task","instanceName":"Isolate Machine","stepType":0},{"identifier":"8394bed9-cd38-416e-a7a2-e8571405b648","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Count
        Entities In Scope","instanceName":"Count Instances","stepType":0},{"identifier":"a37590d3-f491-4bf9-b5e0-3d3b0857b9ef","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Has
        instances or local ips?","stepType":4},{"identifier":"a8ebf631-77cf-4918-8e97-1416899f6333","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"Init Remediation","stepType":0},{"identifier":"baa75471-043b-491a-8984-2d8c21346f5f","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Init
        Remediation Variable","stepType":4},{"identifier":"bd85a32d-91e8-403e-b1c6-ef6878f1e882","integration":"Tools","actionName":"Tools_Set
        Context Value","instanceName":"COMPUTE_INSTANCE_REMEDIATION_SUMMARY ","stepType":0},{"identifier":"c624ac93-5b91-4ded-9457-fab6472f6f4c","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Machine
        Isolated","stepType":4},{"identifier":"e0c2ddb3-8e92-4381-a589-301a7d26fac0","integration":"SiemplifyUtilities","actionName":"SiemplifyUtilities_Count
        Entities In Scope","instanceName":"Count Local IPs","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
