identifier: 12710265-e9a9-4715-9c02-a16d3c5975d1
original_step_id: 12710265-e9a9-4715-9c02-a16d3c5975d1
parent_step_ids:
- 0353496e-a42b-439c-9b2f-2d9288a06bd0
parent_step_id: 0353496e-a42b-439c-9b2f-2d9288a06bd0
previous_result_condition: '{"0353496e-a42b-439c-9b2f-2d9288a06bd0": ""}'
instance_name: Azure Enrichment
is_automatic: true
name: Azure Enrichment
is_skippable: false
description: This block enriches Siemplify Host and User entities with relevant information
    from Azure Active Directory, providing additional context to support investigation
    and response activities.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 120af54a-4a47-495c-bb30-8eaac7d361d3
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"4cbbd500-b494-42cc-86f6-680aa972f939","integration":"AzureActiveDirectory","actionName":"AzureActiveDirectory_Enrich
        User","instanceName":"Enrich User","stepType":0},{"identifier":"a7612a7b-13bb-4317-8ff4-16501a5892ad","integration":"AzureActiveDirectory","actionName":"AzureActiveDirectory_Enrich
        Host","instanceName":"Enrich Host","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
