identifier: 683d22af-3f6c-4399-b7c2-1172ef4f306b
original_step_id: 683d22af-3f6c-4399-b7c2-1172ef4f306b
parent_step_ids:
- 9108e836-96b9-4efa-9dcb-cea6a4201d1a
parent_step_id: 9108e836-96b9-4efa-9dcb-cea6a4201d1a
previous_result_condition: '{"9108e836-96b9-4efa-9dcb-cea6a4201d1a": ""}'
instance_name: Case Tag Size
is_automatic: true
name: Functions_String Functions
is_skippable: false
description: "This action includes basic Pythonic string functions as mentioned below\
    \ - \nLower: Converts the input string to lowercase.\nUpper: Converts the input\
    \ string to uppercase (duplicated case in the script).\nStrip: Removes leading\
    \ and trailing whitespaces from the input string.\nTitle: Converts the first character\
    \ of each word in the input string to uppercase.\nCount: Counts the occurrences\
    \ of `param_1` in the input string.\nReplace: Replaces occurrences of `param_1`\
    \ with `param_2` in the input string.\nFind: Finds the first occurrence of `param_1`\
    \ in the input string and returns its index.\nIsAlpha: Checks if all characters\
    \ in the input string are alphanumeric.\nIsDigit: Checks if all characters in\
    \ the input string are digits.\nRegex Replace: Performs a regex-based replacement\
    \ of `param_1` with `param_2` in the input string.\nJSON Serialize: Converts the\
    \ input string to a JSON formatted string.\nRegex: Finds all occurrences of the\
    \ pattern `param_1` in the input string, joins them using `param_2` (defaulting\
    \ to \", \"), and returns the result.\nDecodeBase64: Decodes the input string\
    \ from base64 using `param_1` as the encoding type. Default to utf-8\nEncodeBase64:\
    \ Encodes the input string in base64 using `param_1` as the encoding type. Default\
    \ to utf-8\nRemoveNewLines: Removes new lines from the input string, replacing\
    \ them with spaces.\nSplit: Splits the input string using `param_1` (or \",\"\
    \ if not provided) and adds the result to the Siemplify result."
action_provider: Scripts
action_name: Functions_String Functions
integration: Functions
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Functions_String Functions
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Param 2":" ","Param 1":"^.{0,100}","Input":"[Event.detection_1_ruleName]","Function":"Regex"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
