identifier: 0353496e-a42b-439c-9b2f-2d9288a06bd0
original_step_id: 0353496e-a42b-439c-9b2f-2d9288a06bd0
parent_step_ids:
- 8cf602e7-523d-4a15-a12a-1c2a8fdfd755
parent_step_id: 8cf602e7-523d-4a15-a12a-1c2a8fdfd755
previous_result_condition: '{"8cf602e7-523d-4a15-a12a-1c2a8fdfd755": ""}'
instance_name: High Risk Users Check
is_automatic: true
name: High Risk Users Check
is_skippable: false
description: This block checks Google GTI sourced alerts against a SOAR custom list
    to find matches of targeted Industries.
action_provider: Flow
action_name: NestedAction
integration: Siemplify
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: block
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: null
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowIdentifier
    value: 82cf122c-0ef9-41ee-be12-eebfb231ec41
-   step_id: null
    playbook_id: null
    name: NestedWorkflowInputs
    value: '[]'
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: NestedWorkflowSteps
    value: '[{"identifier":"63a93b87-8082-48af-9d09-0e089e5ec13d","integration":"Flow","actionName":"IfFlowCondition","instanceName":"Are
        there Matches","stepType":4},{"identifier":"a10c13d2-6f18-476e-afde-d85ca3da96ee","integration":"Tools","actionName":"Tools_Add
        Alert Scoring Information","instanceName":"Add High Severity Record","stepType":0},{"identifier":"ee383fa5-da2d-4114-a3b1-86b29830ddba","integration":"Lists","actionName":"Lists_Search
        Environment Custom Lists","instanceName":"Retrieve Relevant Users","stepType":0},{"identifier":"f13e28d5-65ae-46fe-8324-2292416f2186","integration":"TemplateEngine","actionName":"TemplateEngine_Render
        Template","instanceName":"Find Matches","stepType":0}]'
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
