identifier: bc70db0d-4296-4ebd-a336-fa695e2846ff
original_step_id: bc70db0d-4296-4ebd-a336-fa695e2846ff
parent_step_ids:
- 2f800da4-e815-420b-9128-f512bb676977
parent_step_id: 2f800da4-e815-420b-9128-f512bb676977
previous_result_condition: '{"2f800da4-e815-420b-9128-f512bb676977": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
