identifier: 62b56cc8-40f2-4297-ac2f-f50eddc71fb5
original_step_id: 62b56cc8-40f2-4297-ac2f-f50eddc71fb5
parent_step_ids:
- 653afb59-6004-4e6f-9827-ed81af79cbb5
parent_step_id: 653afb59-6004-4e6f-9827-ed81af79cbb5
previous_result_condition: '{"653afb59-6004-4e6f-9827-ed81af79cbb5": ""}'
instance_name: Machine Logon Users
is_automatic: true
name: MicrosoftDefenderATP_Get Machine Logon Users
is_skippable: false
description: Get Machine Log on users
action_provider: Scripts
action_name: MicrosoftDefenderATP_Get Machine Logon Users
integration: MicrosoftDefenderATP
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: MicrosoftDefenderATP_Get Machine Logon Users
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
