identifier: fa138fdb-72ad-4598-be4b-ee8171900d90
original_step_id: fa138fdb-72ad-4598-be4b-ee8171900d90
parent_step_ids:
- 62b56cc8-40f2-4297-ac2f-f50eddc71fb5
parent_step_id: 62b56cc8-40f2-4297-ac2f-f50eddc71fb5
previous_result_condition: '{"62b56cc8-40f2-4297-ac2f-f50eddc71fb5": ""}'
instance_name: MicrosoftDefender File Related Alerts
is_automatic: true
name: MicrosoftDefenderATP_Get File Related Alerts
is_skippable: false
description: 'Get File Related Alerts. Note: For this action only SHA1 is supported'
action_provider: Scripts
action_name: MicrosoftDefenderATP_Get File Related Alerts
integration: MicrosoftDefenderATP
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: MicrosoftDefenderATP_Get File Related Alerts
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Status":"Unknown, New, InProgress, Resolved","Severity":"UnSpecified,
        Informational, Low, Medium, High","Category":"","Incident ID":""}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
