identifier: 5a36205e-3ff2-4e1a-8fe0-7619db3b4b7c
original_step_id: 5a36205e-3ff2-4e1a-8fe0-7619db3b4b7c
parent_step_ids:
- c015d594-aa02-48dc-bff3-d35520392cbf
parent_step_id: c015d594-aa02-48dc-bff3-d35520392cbf
previous_result_condition: '{"c015d594-aa02-48dc-bff3-d35520392cbf": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
