identifier: 50b1687c-a160-4ecd-ae87-1c91062a772b
original_step_id: bdfe9872-9aa4-438d-962c-36be46b53cc0
parent_step_ids:
- faf20e08-accc-4592-b0df-870b3c1b49de
parent_step_id: faf20e08-accc-4592-b0df-870b3c1b49de
previous_result_condition: '{"faf20e08-accc-4592-b0df-870b3c1b49de": ""}'
instance_name: Enrich User
is_automatic: true
name: AzureActiveDirectory_Enrich User
is_skippable: false
description: Enrich Siemplify User entity with information from Azure Active Directory.
    Action expects Siemplify user entity in username@domain format.
action_provider: Scripts
action_name: AzureActiveDirectory_Enrich User
integration: AzureActiveDirectory
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: AzureActiveDirectory_Enrich User
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Fields To Return":"accountEnabled,ageGroup,assignedLicenses,businessPhones,city,companyName,consentProvidedForMinor,country,createdDateTime,creationType,department,displayName,mail,employeeId,employeeHireDate,employeeOrgData,employeeType,onPremisesExtensionAttributes,externalUserStateChangeDateTime,faxNumber,givenName,imAddresses,identities,externalUserState,jobTitle,surname,lastPasswordChangeDateTime,legalAgeGroupClassification,mailNickname,mobilePhone,id,officeLocation,onPremisesSamAccountName,onPremisesDistinguishedName,onPremisesDomainName,onPremisesImmutableId,onPremisesLastSyncDateTime,onPremisesProvisioningErrors,onPremisesSecurityIdentifier,onPremisesSyncEnabled,onPremisesUserPrincipalName,otherMails,passwordPolicies,passwordProfile,preferredDataLocation,preferredLanguage,proxyAddresses,signInSessionsValidFromDateTime,sponsors,state,streetAddress,usageLocation,userPrincipalName,userType,postalCode,authorizationInfo,deletedDateTime,showInAddressList,isResourceAccount,refreshTokensValidFromDateTime"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
parallel_actions: []
step_debug_data: null
