identifier: d9b9c0ba-99d3-4ce7-9510-f5fe0f2a74ab
original_step_id: c31613a0-3b00-4486-823f-b0f459dbe4f2
parent_step_ids:
- 50b1687c-a160-4ecd-ae87-1c91062a772b
parent_step_id: 50b1687c-a160-4ecd-ae87-1c91062a772b
previous_result_condition: '{"50b1687c-a160-4ecd-ae87-1c91062a772b": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
