identifier: 9b616f2f-e167-49df-9d11-50b548c8c009
original_step_id: e7fef913-bf5b-48ca-865c-8ae0ed813e7d
instance_name: Count Ec2
is_automatic: true
name: SiemplifyUtilities_Count Entities In Scope
is_skippable: false
description: Count the number of entities from a specific scope.
action_provider: Scripts
action_name: SiemplifyUtilities_Count Entities In Scope
integration: SiemplifyUtilities
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '86400'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '3600'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: 06477888-9352-42ba-a080-e623e2a20148
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: SiemplifyUtilities_Count Entities In Scope
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"Entity Type":"HOSTNAME"}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: AWS EC2 Filter.SelectedEntities
parallel_actions: []
step_debug_data: null
