identifier: 9acc6eb3-a9aa-44fc-8b80-525bb2e882b7
original_step_id: b7049ab8-fa6e-4979-84f8-12e56dc2b820
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: 'False'
parallel_actions: []
step_debug_data: null
