identifier: d11d177c-366a-4258-8f4e-f90bd2ace866
original_step_id: 214c8afe-9414-4460-97aa-e720b25c7c9f
parent_step_ids:
- 66f7558f-0c25-4eda-ac11-f82c6d44d9b2
parent_step_id: 66f7558f-0c25-4eda-ac11-f82c6d44d9b2
previous_result_condition: '{"66f7558f-0c25-4eda-ac11-f82c6d44d9b2": "1"}'
instance_name: Output_2
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: '[Stop Instances.is_success]

        '
parallel_actions: []
step_debug_data: null
