identifier: e0dec0a9-3ddc-4d50-8408-cafb251b0734
original_step_id: e1b0e750-0315-436d-be90-37d181ba2e43
parent_step_ids:
- cbc7d95f-7f49-440d-a76d-3eeee8c862b7
parent_step_id: cbc7d95f-7f49-440d-a76d-3eeee8c862b7
previous_result_condition: '{"cbc7d95f-7f49-440d-a76d-3eeee8c862b7": ""}'
instance_name: List Roles
is_automatic: true
name: Okta_List Roles
is_skippable: false
description: Lists all roles assigned to a user
action_provider: Scripts
action_name: Okta_List Roles
integration: Okta
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Okta_List Roles
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"User IDs":"[User Details.JsonResult| \"id\"]","Also Run On Scope":false}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: null
parallel_actions: []
step_debug_data: null
