identifier: edf56fbf-3b92-4f1e-b168-1054ef8bdd71
original_step_id: 27f20e2d-1c6f-42cf-baa2-af91786f55fa
parent_step_ids:
- df5354ae-0caf-44c1-a2b0-37385f08a9de
parent_step_id: df5354ae-0caf-44c1-a2b0-37385f08a9de
previous_result_condition: '{"df5354ae-0caf-44c1-a2b0-37385f08a9de": ""}'
instance_name: Output_1
is_automatic: true
name: Output
is_skippable: false
description: ''
action_provider: Flow
action_name: OutputAction
integration: Flow
auto_skip_on_failure: false
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: output
parameters:
-   step_id: null
    playbook_id: null
    name: NestedWorkflowOutput
    value: null
parallel_actions: []
step_debug_data: null
