identifier: cbc7d95f-7f49-440d-a76d-3eeee8c862b7
original_step_id: a88dca56-6ae2-4bb0-8aab-6bdfc8d38866
parent_step_ids: []
parent_step_id: ''
previous_result_condition: '{}'
instance_name: User Details
is_automatic: true
name: Okta_Get User
is_skippable: false
description: Get information about a user
action_provider: Scripts
action_name: Okta_Get User
integration: Okta
auto_skip_on_failure: true
is_debug_mock_data: false
parent_container_id: null
is_touched_by_ai: false
start_loop_step_id: null
type: action
parameters:
-   step_id: null
    playbook_id: null
    name: AssignedUsers
    value: null
-   step_id: null
    playbook_id: null
    name: AsyncActionTimeout
    value: '3600'
-   step_id: null
    playbook_id: null
    name: AsyncPollingInterval
    value: '300'
-   step_id: null
    playbook_id: null
    name: DynamicInjectionInstancePlaceholder
    value: null
-   step_id: null
    playbook_id: null
    name: FallbackIntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: FetchInstanceByName
    value: 'false'
-   step_id: null
    playbook_id: null
    name: HasApprovalLink
    value: null
-   step_id: null
    playbook_id: null
    name: IntegrationInstance
    value: null
-   step_id: null
    playbook_id: null
    name: MessageToAssignee
    value: null
-   step_id: null
    playbook_id: null
    name: PendingActionTimeout
    value: null
-   step_id: null
    playbook_id: null
    name: ScriptName
    value: Okta_Get User
-   step_id: null
    playbook_id: null
    name: ScriptParametersEntityFields
    value: '{"User Ids Or Logins":"[Event.event_principal_user_emailAddresses]","Also
        Run On Scope":false}'
-   step_id: null
    playbook_id: null
    name: SelectedScopeName
    value: All entities
-   step_id: null
    playbook_id: null
    name: UseEntitiesLoopScope
    value: null
parallel_actions: []
step_debug_data: null
